### ISSUE TITLE
[QUESTION] 3-phase async dispatch

### ISSUE THREAD

**Issue by johanneslumpe** [gaearon/redux#100]
In Flummox we had the ability to auto-dispatch `begin`, `success` and `failure` actions. I assume in redux we can do this by creating a custom middleware, which could inspect the type of the action which returned the promise and then dispatched a success or failure action depending on whether the promise gets resolved or rejected. Does this sound correct to you? If so, would it make sense to include something like this as stock middleware in redux?

**Comment by gaearon** [comment]
I was thinking of something like this:

https://github.com/gaearon/redux/issues/99#issuecomment-112198579

As discussed in Slack, it might be better to create an organization and have a few “blessed” middlewares coming from it, with separate versioning from Redux.

**Comment by gaearon** [comment]
Oh wait, I actually meant this: https://github.com/gaearon/redux/issues/99#issuecomment-112212639

(Which is why it should have separate versioning lol)

**Comment by johanneslumpe** [comment]
Yeah I agree. But something like you mentioned on the other issue seems like it would be a good candidate for one such middleware. Maybe not in the exact way, but similar (I'm still trying to figure out how to use less constants ;) )

**Comment by goatslacker** [comment]
Can we also have an auto-dispatch `after` action which works kinda like `finally`?

**Comment by johanneslumpe** [comment]
so a 4-phase dispatch - begin, success/failure, end. @goatslacker what would you use `after` or `end` for? to make sure that certain stores only get notified after other stores processed the success or failure dispatches?

**Comment by acdlite** [comment]
@johanneslumpe There's only one store.

**Comment by acdlite** [comment]
See @gaearon's comment about composing stores in lieu of `waitFor()` https://gist.github.com/gaearon/d77ca812015c0356654f

**Comment by gaearon** [comment]
I'm closing as not a real issue, but I'd be happy to see some middleware outside the core!
