### ISSUE TITLE
babel loose all

### ISSUE THREAD

**Issue by dariocravero** [gaearon/redux#115]
@acdlite flummox [is using `"loose": "all"` in `.babelrc`](https://github.com/acdlite/flummox/blob/master/.babelrc#L3). Babel [says that we would have some speed gains](https://babeljs.io/docs/advanced/loose/) from using it but that it might be risky. What are your thoughts/experience with it in flummox so far? Should we include that into redux as well?

**Comment by acdlite** [comment]
It's for IE8 support.

**Comment by acdlite** [comment]
As long as we're careful to avoid the edge cases, I'm :+1: for using loose mode.

**Comment by chicoxyzzy** [comment]
loose mode FTW

**Comment by gaearon** [comment]
I'm OK if we're not breaking anything

**Comment by dariocravero** [comment]
:) good stuff.
I'll bring it in as part as #88 if you're ok with it then as I've just finished putting together a `browser` version of the library like flummox has (kindly borrowing its scripts for webpack as I was always using browserify so far).

**Comment by chicoxyzzy** [comment]
I'm still don't sure if we need `babel-runtime`. see https://github.com/gaearon/redux/pull/114#issuecomment-112603679

**Comment by ooflorent** [comment]
Previous version of Babel hadn't decorators support in loose mode.
It seems to be fixed. :+1:

**Comment by ooflorent** [comment]
Fixed in dd831886fa068a1a306844492d982fbcc9fb3ed2
