### ISSUE TITLE
Boilerplate or REST API example

### ISSUE THREAD

**Issue by swordsreversed** [gaearon/redux#116]
Can anyone point me to a repo consisting of either of these?

**Comment by tsingson** [comment]
REST example ?  meaning the server side RESTful or client side AJAX ( async to access REST ) ?

**Comment by swordsreversed** [comment]
Both, just a repo showing CRUD on the server and redux/react on the server. You have?

**Comment by tsingson** [comment]
for client side,   [Nicola Molinari's redux example](https://github.com/emmenko/redux/tree/master/examples) is good .

for server side, sorry, i don't have javascript , but golang CRUD RESTfull backend only. 
i should send to you if need really.

**Comment by emmenko** [comment]
Yeah you can have a look at that example

PS: the correct link is this https://github.com/emmenko/redux/tree/async-with-router/examples

Also, that example will be improved and maintained here https://github.com/emmenko/redux-react-router-async-example

**Comment by swordsreversed** [comment]
great, thanks. might be good in the readme, as alt does. https://github.com/goatslacker/alt#examples
