### ISSUE TITLE
Hot reload of components failing on some edge cases

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux#128]
I can't pinpoint *exactly* what is needed for this to happen (I have a pretty complicated setup at the moment), but in some cases I'm getting “This probably means the DOM was unexpectedly mutated” invariant violation on hot reload.

It seems related to hot reloading calling `forceUpdate`, which in turn causes `Provider#componentWillReceiveProps`, dispatcher replacing, and `setState` on the `Connector` components below in the tree that receive a new `select` prop.

The simple fix is to put a `setTimeout` when receiving a new dispatcher in `Provider`:

```js
        if (redux !== nextRedux) {
          setTimeout(() => {
            const nextDispatcher = nextRedux.getDispatcher();
            redux.replaceDispatcher(nextDispatcher);
          });
        }
```

I'm not a fan of this solution so I'll just leave this here for posterity and try to figure out the root issue later. Might be a React bug after all.

**Comment by gaearon** [comment]
Actually I think we should just do this now so other people don't have the same problem, and later find out what's wrong. Any objections

**Comment by gaearon** [comment]
Meh, I had the classic “duplicate React” problem because of `npm link`.

![batman-facepalm](https://cloud.githubusercontent.com/assets/810438/8211608/250ae772-1520-11e5-9a77-fa5de243dcb1.jpg)

**Comment by johanneslumpe** [comment]
Glad to see it does not only happen to me ;)

**Comment by emmenko** [comment]
@gaearon well, there are still cases like `componentDidMount`. Have you found a solution for that yet, or is it simply not possible?

See also https://github.com/gaearon/react-hot-loader/issues/64

**Comment by gaearon** [comment]
Well, at least changing `componentDidMount` doesn't blow up the app. :-)
I plan to solve the problem you linked to in the next version of RHL, but it's a different issue.

**Comment by emmenko** [comment]
You mean `react-hotify` ?

**Comment by gaearon** [comment]
Yup.

**Comment by emmenko** [comment]
:+1:
