### ISSUE TITLE
Missing usage of 'incrementIfOdd' in example

### ISSUE THREAD

**Issue by jviereck** [gaearon/redux#13]
Hi there,

reading the `Readme.md` file I see the `incrementIfOdd` function defined there BUT I cannot make up how to use it and it seems to be not used in the example either - should these actions just be passed as `actions` to the `<Container ...>` as well, like this...?

```js
export default class CounterContainer {
  render() {
    // stores can be a single store or an array.
    // actions can only be a string -> function map.
    // props passed to children will combine these actions and state.
    return (
      <Container stores={counterStore}
                 actions={{ increment, decrement, incrementIfOdd }}>
        {props => <Counter {...props} />}
      </Container>
    );
  }
}
```
Thanks a lot in advance :)

PS: Thanks for starting this new flux implementation - the work you and the awesome contributors have done so far is really inspirational :)

**Comment by dariocravero** [comment]
Hi @jviereck by the look of things [Container is sending down both, the store's states and its actions to Counter](https://github.com/gaearon/redux/blob/master/src/Container.js#L68-L71). `{props => <Counter {...props} />}` is essentially what gives you the values inside your `Counter` component and [that's where you would be using it](https://github.com/gaearon/redux/blob/master/examples/counter/Counter.js#L11). The framework looks indeed very promising :D

**Comment by gaearon** [comment]
Yes, you could do that! I don't really use it in the example (it's a silly function). It's just an example of "look into state from action creator" API that I verify still works after major changes. Of course I should just add tests instead.
