### ISSUE TITLE
Proposal: Rename "stores" to "reducers"

### ISSUE THREAD

**Issue by acdlite** [gaearon/redux#137]
If I remember correctly, @gaearon, you said we'd make this change once Redux hit 500 stars. :)

It would also be nice to have a "Terminology" section of the docs so we can keep everyone on track. I've especially noticed that we currently use the word "dispatcher" to refer to *at least* three different things.

**Comment by goatslacker** [comment]
-1 the learning curve on this repo already feels steep. Let's not make it any steeper by introducing new terminology for new flux users. 

Internally they can be called reducers, publicly keep them as stores so it's easier to grok.

**Comment by acdlite** [comment]
I honestly think it's more confusing the way it is now. Totally anecdotal, but I've had several people IRL get all messed up thinking that the stores were stateful.

The main characteristics of "stores" in traditional Flux are that they 1) hold state, and 2) emit change events. Neither of which are true in Redux.

**Comment by emmenko** [comment]
I agree we need to clarify the terminology, and in some cases find better naming. 
I think as a first step there should be some JSDoc, then a terminology section would also help.
In general we have to maintain a certain level of consistency.

**Comment by gaearon** [comment]
I wonder if there's a term that doesn't sound FP-ish but is not a “store”.
Domains?

**Comment by gaearon** [comment]
OTOH it's already called Redux so at least “reducer” sounds related.

**Comment by leoasis** [comment]
How about "step updates", or "steppers", which moves your state one step forward. I've seen this being used in Elm literature, having a function called `step`, `update`, or `next`

**Comment by goatslacker** [comment]
Domains contain node.js baggage. 

They're not stores in how they function but you still put your state logic in there much like flux stores. They're state managers, like flux stores are supposed to be. 

Reducers is fine if you're keen on changing its name though.

**Comment by acdlite** [comment]
Especially because "reducer" is a precise description of what they actually are :)

**Comment by gaearon** [comment]
Updaters? Sounds descriptive + less snobbish than reducers.

**Comment by emmenko** [comment]
I like `reducer` as well

**Comment by acdlite** [comment]
I guess I don't see why "reducer" is snobbish. Isn't it better to use the actual term than invent a new one that is less descriptive?

**Comment by leoasis** [comment]
I guess both may be valid, and it depends from which point of view you see it: a _reducer_ of actions (into state), or an _updater_ of state.

**Comment by acdlite** [comment]
"Updater" implies that its mutative. "Reducer" makes it clear that you're returning a new state, not modifying the old one.

**Comment by leoasis** [comment]
That's a strong point in favor I think, may help with the issue about redux not working correctly with mutations

**Comment by acdlite** [comment]
I do appreciate the need to keep Redux friendly to people who aren't familiar with FP, but we can solve that with better documentation. I like the current docs, but on first glance they're a bit overwhelming. A good docs site that foregrounds the familiar stuff (action creators, reducer logic) over the advanced stuff (middleware, hot reloading) would be very helpful.

And yet, judging from the rapid growth of the following here, we must be doing something right :)

**Comment by gaearon** [comment]
I'm open to changing “Stores” to “Reducers” if this happens together with better docs.

**Comment by gaearon** [comment]
The essential element is to preserve the “it's like Flux but better, don't worry” vibe. I don't want people to think it's similar to Reflux or something, which sounds like Flux but breaks some of its nice properties. I also don't want them to think they need to learn FP. As long as we can keep it so, I'm okay with this change.

**Comment by acdlite** [comment]
Suggestion I'm less sure about: If we rename change the Redux class to Store (think about it: its two functions are to hold state and emit change events) then the top-level API becomes:

```js
const store = createStore(reducers);

<Provider store={store} />
```

This communicates the idea pretty well, I think. Reducers are where your store logic goes, but they are not stores themselves.

**Comment by gaearon** [comment]
I like this although `store.dispatch` feels wrong then.

**Comment by acdlite** [comment]
Yeah that's the one thing I don't really like, but the other methods makes sense: `store.getState()`, `store.setState()`, `store.subscribe()`

**Comment by gaearon** [comment]
Now that I think of it, we're not really “dispatching” anything.
Ugh, naming is a rabbit hole.

**Comment by emmenko** [comment]
Ok, so what we have so far are:
- action (creators)
- (store) reducer
- middleware functions
- callback (listener) functions
- something that triggers the functions call chain (called dispatcher)
- something that holds the mutable state (with setters and getters)

Maybe we can take a step back and re-think the naming?

**Comment by gaearon** [comment]
Maybe `store.dispatch` is not too bad. We can just explain that instead of many Stores, we have a single Store, and you compose it from Reducers. No Stores = no need for a separate Dispatcher, so `dispatch` is available right on Store.

**Comment by acdlite** [comment]
@gaearon I agree.

@emmenko Good summary. Any terminology breakdown should distinguish between *action creators* and *actions*. It should also distinguish between the *dispatcher* or *dispatch strategy*, which encompasses middleware + reducers, as well as the *dispatch* method which triggers a *dispatch cycle*.

**Comment by gaearon** [comment]
Let's do this:

* Rename Stores to Reducers
* Rename the “Redux instance” to Store as per https://github.com/gaearon/redux/issues/137#issuecomment-113252359
* Explain that if you squint at traditional Flux Stores, you'll see Reducers trapped in them

Anybody want to lead the new docs effort? It'll need some structuring: a glossary, a README, a simple “get-it-running” tutorial, and maybe an more in-depth “design decisions” guide.

**Comment by acdlite** [comment]
@gaearon I'll volunteer to lead this :) I have an outline started already.

**Comment by gaearon** [comment]
Thanks :+1:

**Comment by emmenko** [comment]
> I'll volunteer to lead this

Thanks! :+1: :+1: :+1: 

Personally, as a final outcome, I would really like to have an auto-generated website with:
- getting started
- tutorials
- live examples

...and as a nice-to-have feature:
- generated documentation a-la `docco` (e.g.: like `jasmine`) so that the source code is clearly explained

But starting with markdown and jsdoc is of course a first step ;)

**Comment by acdlite** [comment]
Right, I think the first step is getting the docs written in Markdown form, then we can port them to a really nice docs site. :+1: for JSDoc, too. I'm going to take one final stab at https://github.com/gaearon/redux/pull/87 tonight but I'm not sure Flow annotations are worth it at this point unless we rid the codebase of function overloading. (Or unless someone teaches me how to properly type them without Flow complaining.)

**Comment by emmenko** [comment]
I guess Flow is not a priority atm.

**Comment by jordangarcia** [comment]
+1 for stores being called reducers.

I've not been fond of calling these more declarative, stateless things stores.

**Comment by aaronjensen** [comment]
I like the new name ideas. I'd also propose renaming `Connector` to something like `Subscription`. `Connector` is very generic, and while I get that it is connecting redux's state and dispatcher to its children, I think that a subscription is a better description of what is happening. It's a bit of a stretch that you get a dispatcher along w/ your subscription, but I think that's ok.

**Comment by ianp** [comment]
-1 for stores being called reducers, as a name it's not very intuitive for new users (at least those without a functional programming background). Maybe Updater or Transformer would be better, or Store Updater if we wanted to be more explicit about it.

**Comment by gaearon** [comment]
“Transformer” has been suggested quite a few times. It doesn't suggest mutable nature like Updaters, is more approachable than Reducers, and doesn't carry the “storage” connotation of Stores.

How do you like Transformers?

**Comment by gcanti** [comment]
+1 for Reducers

**Comment by gaearon** [comment]
As noted by @faassen on Twitter, a good argument for “reducers” is calling back to the project name. We have a chance to say “This is like Flux, but there is a single Store. Just like you can compose your app into React components, in Redux, you compose that Store out of Reducers. They are called Reducers because their signature matches function passed to `[].reduce()`: `(state, action) => state`. Bla bla bla”

**Comment by ryanflorence** [comment]
angular spread like wildfire and uses words like

- directive
- isolate
- transclude

If they don't store data, don't call them stores.

Ignoring programming, transforming and reducing are different things. I'd pick the name that is the most accurate.

Are you transforming from one form to another or are you reducing from many values to one?

**Comment by cef62** [comment]
I'm for `reducers` too! :+1:

**Comment by staltz** [comment]
Take inspiration from Elm. https://github.com/evancz/elm-architecture-tutorial#the-basic-pattern

The best word would be `update`. Store is nonsense, it has always been "Model". No need to reinvent the wheel or confuse people.

**Comment by gaearon** [comment]
My beef with calling them updaters is people might think they are supposed to be mutative. If we naming can help clarify non-mutative nature that would be a huge bonus.

>Are you transforming from one form to another or are you reducing from many values to one?

I'm accumulating. “How an action turns a state into the next state.” Conceptually they're reducing over many actions from the initial (undefined) state, and memoization is just an optimization.

**Comment by ajaybeniwal** [comment]
State Transformer

**Comment by staltz** [comment]
Try to avoid reinventing/rediscovering as much as possible. People have been calling it `reduce`, `scan`, `fold`, and

**Comment by grayj** [comment]
I'm a few days from getting to dig back into this, so a bit of a blind perspective:

Does it take a bunch of sources and reduce them into a store-like interface which is then consumed the way you'd consume a store in Flux?

If so, reducers is at least giving me the correct impression.

**Comment by lionelB** [comment]
reducer seems to be accurate from a javascript perspective... 
Don't see the value to name it from a concept of another language, even if it's more accurate.

**Comment by jonrh** [comment]
Don't have a firm stand on what it should be but IMO it should be something that most accurately represents the type of computation. If it's an umfaliar word to most programmers then that can be offset by documentation.

**Comment by vramana** [comment]
Looking from a FP perspective, current stores looks like more like a 'map' rather than a 'reduce'. Instead of a function, we have an action here . I propose the name `actionMapper`. 

And I am not the first one also to think like this @emmenko had already used this name in his redux react-router example here https://github.com/emmenko/redux-react-router-async-example/blob/master/lib/stores/github.js#L13.

**Comment by leoasis** [comment]
@vramana it is not a `map`, it is a `reduce`, since it takes the previously accumulated `state` and a new `action` and returns a new `action`.

If you had an array of actions, you'd use this function to reduce it:

```js
function reducer(state, action) {
  // switch (action.type) ...
  // return state;
}
const finalState = allAppActions.reduce(reducer, initialState);
```

**Comment by slorber** [comment]
I like to think of it as a projection (of an event log to a data structure).
DB people used to call this "materialized views".

I like reduce or fold, it is well understood by different communities

**Comment by ianp** [comment]
I much prefer Transformers to Reducers: it's clear what it means from the normal English usage of the word.

**Comment by ntkoso** [comment]
Reducers. First, it's javascript library and javascript uses `[].reduce(reducer, state)`. Second, Redu(cer)x is already in library name.

**Comment by matthewwithanm** [comment]
Reducer is accurate and has a precedent in vanilla JS. Not sure how that could be improved on.

**Comment by gaearon** [comment]
Reducers it shall be then.

**Comment by gaearon** [comment]
(Follow progress in #140)

**Comment by gaearon** [comment]
Occasionally I find old discussions calling them “stores” and marvel at how ridiculously confusing it was in the hindsight.

**Comment by kof** [comment]
"state container"?

**Comment by goatslacker** [comment]
Yes this was a good change :)
