### ISSUE TITLE
Bring back HOCs on top of the container components

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux#14]
As per https://github.com/gaearon/redux/issues/5#issuecomment-108261992, let's bring back HOCs, but this time built on top of the container components. Container components are lower level.

This work would include:

* Change `root` to be a container component called `Root`
* Implement `root` and `container` as HOCs that wrap the components
* I want to keep using `root` HOC + `Container` component in the examples
* Tricky file naming. I guess let's put them into `addons` folder but keep `root` etc as the export name.

@hugobessaa

**Comment by ooflorent** [comment]
See #15

**Comment by gaearon** [comment]
Oh, cool. Can you please bring this up to date with the todo list in this issue?

**Comment by hugobessaa** [comment]
You were too fast. I'm commuting :rocket:

Let us know if you want help implementing the other things in the todo list

**Comment by gaearon** [comment]
Done now.
