### ISSUE TITLE
Debug mode for TODO example

### ISSUE THREAD

**Issue by emmenko** [gaearon/redux#148]
I was thinking it would make the example even more awesome if you can actually see (visually) what's going on behind the scenes. 

Something along [this](https://reactiflux.slack.com/files/gaearon/F06DWKR5F/screen_shot_2015-06-16_at_22.15.00.png), with a toggle to show it or not.

What do you think?

/cc @vramana @gaearon

**Comment by goatslacker** [comment]
I would venture a guess that this would happen after React Europe.

**Comment by vramana** [comment]
Definitely yes. But how about adding the debug pane like an addon to the Provider? Just plug and play to work with any redux application.

**Comment by johanneslumpe** [comment]
@vramana afaik this is what is planned at some point for easy debugging

**Comment by gaearon** [comment]
There is an interesting work in progress on this, but it will be shown on React Europe.
Stay tuned.

**Comment by gaearon** [comment]
My ReactEurope talk in which I show off (soon to be released) Redux DevTools: https://www.youtube.com/watch?v=xsSnOQynTHs

Closing in favor of #113.
