### ISSUE TITLE
Provide a 'starter-kit' example that uses Redux + best practices

### ISSUE THREAD

**Issue by zavelevsky** [gaearon/redux#152]
The TODO-MVC example is a step in the right direction but it doesn't include many of the aspects (css to name one). To make it easier for a complete beginner to choose Redux - there should be a starter kit based on React, Redux, hot-reload, webpack, some local CSS solution, etc.

**Comment by emmenko** [comment]
You can find a more complete example here, which is officially maintained
https://github.com/emmenko/redux-react-router-async-example

We are planning to improve the documentation anyway. See https://github.com/gaearon/redux/pull/140
