### ISSUE TITLE
Original examples were removed when Todomvc was added

### ISSUE THREAD

**Issue by mikekidder** [gaearon/redux#154]
Was this intentional? 

The README.md still speaks to it as an introduction, which it should..

In addition, have mixed sections when going down the page:

- counter sample screenshot 
- running todomvc (which really talks to building redux, then todomvc) 
- back to counter sample actions, stores, etc..

**Comment by vramana** [comment]
@mikekidder I am removed them temporarily. I am adding them back in #150.

**Comment by vramana** [comment]
@gaearon You can close this now I guess.
