### ISSUE TITLE
Tests in examples

### ISSUE THREAD

**Issue by dariocravero** [gaearon/redux#157]
Hi all,

I think we need some tests in our examples to show a way to go about it at least :).

What do you think about that?

Here are some I've written for panels-contexts: [actions](https://github.com/UXtemple/panels-contexts/blob/master/__tests__/actions-test.es6), [reducer](https://github.com/UXtemple/panels-contexts/blob/master/__tests__/reducer-test.es6) and [getters](https://github.com/UXtemple/panels-contexts/blob/master/__tests__/getters-test.es6).

Perhaps when the todomvc example settles we can add something like that?
Cheers,
Darío

**Comment by gaearon** [comment]
I'd appreciate somebody contributing tests to the examples. Do you want to take this?

**Comment by dariocravero** [comment]
I'm happy to do so but it probably won't be until next week. Would that be ok?

**Comment by gaearon** [comment]
Yeah sure! (If somebody else would like to take this before you start, feel free to write here.)

**Comment by dariocravero** [comment]
ref [faking redux](https://github.com/UXtemple/panels-router/blob/master/__tests__/history-test.es6#L19-L22)

**Comment by gaearon** [comment]
Just a reminder this is still up for grabs!
If somebody wants to help please make sure you do it on top of `breaking-changes-1.0` branch.

**Comment by gaearon** [comment]
Superseded by #278.
