### ISSUE TITLE
Common reducers formulas

### ISSUE THREAD

**Issue by dariocravero** [gaearon/redux#162]
Now that reducers are only functions, I wonder if we could abstract certain patterns to do some common reducing operation (say, CRUD (well the R would be a getter :P)) and create a repo, wiki, (generator?) or something that would contain (and explain) them so that we don't have to reinvent the wheel every time :). It could be as specific or vague as one would want it to be, i.e., it could include any of the following: a reducer, actions, (containers), etc. with their tests.

If there's enough interest I can start drafting some...

**Comment by gaearon** [comment]
We need to popularize the idea of higher-order reducers. These are reducers that take your existing reducers, but amend them with some stock functionality (pagination, todo/redo, etc).

Like HOCs, but for reducers :-)

**Comment by dariocravero** [comment]
Sounds like a plan! :)

**Comment by gaearon** [comment]
Oh wait.. These *are* transducers aren't they

**Comment by gaearon** [comment]
Closing in favor of #176
