### ISSUE TITLE
Document Redux flow in more details

### ISSUE THREAD

**Issue by asaf** [gaearon/redux#163]
I'm not sure if this may somehow fall into #89 (Assuming a nice web site is generated and there's a good location in the source code to describe it) or not, but it'll be helpful to have the full flow documented,

The "How do Stores, Actions and Components interact?" is a good starting point but it's too general,

I wanted to open this issue few days ago but I couldn't wait any longer when I suddenly found out that `INIT_ACTION` is being invoked initially :)

Feel free to close if you feel like this is irrelevant.

**Comment by gaearon** [comment]
This will be fixed by #140.
