### ISSUE TITLE
parameterized actions

### ISSUE THREAD

**Issue by faassen** [gaearon/redux#168]
In Flummox (pinging @acdlite ), you can parameterize actions: they're in a class, and you can pass the parameters to `createActions`. I use this facility to create a parameterized React component which maintains its own Flux instance (equivalent to a Redux instance). I have two concrete use cases for parameterized actions so far:

* pass in a URL. This URL is then used to load the initial content in an action. This content contains other URLs that can be used in other actions. The whole content is loaded like this, i.e. my code uses a hypermedia API. There are no hardcoded URLs in the client at all except a single one to start the whole process with.

* pass something I'd like to mock or replace, such as the `fetch` function (HTTP fetch API), which I'd like to mock during testing or development.

In Redux however, actions are not part of a class instance, but they're simple top-level functions. `bindActionCreators` makes assumptions that I don't think work with a class instance. Besides, I would need to get that class instance into the React component somehow, which also seems difficult.

So any suggestions on how to deal with this use case in Redux? I could of course pass in the parameters each time by hand, but that seems cumbersome. Perhaps the right way is to treat them as part of the state, which can then be initialized with a special initialization action?

**Comment by gaearon** [comment]
You don't really have to use `bindActionCreators`, you can just pass `dispatch` down instead.

Does this help:

```js
function makeMyOwnAwesomeActions(baseUrl) {
  return {
    doSomething(param) {
      return ...;
    },
    doSomethingElse(otherParam) {
      return ...;
    }
  };
};


const myActions = makeMyOwnAwesomeActions('http://google.com');

class MyComponent {
  doSomething() {
    this.props.dispatch(myActions.doSomething(42));
  }
}
```

**Comment by faassen** [comment]
Yes, I realized I could do dispatch manually, but the example won't help, as makeMyOwnAwesomeActions gets run during module import time, which is too early. Running it later on, just before dispatch, raises the whole "where does the data come from" question, though -- that's a bit too late. The outer component where the redux object is initialized is the one that knows these parameters.

The parameters need to be initialized later than that. In the Flummox setup I have now the flux instance (with parameter) plus its initial data load is triggered in a `componentWillMount`. The flux object is part of the object state.

But I suspect I can do something similar by stuffing it in the state with a special initialization action, and then letting the other actions use that part of the state to do its work. It all ties into patterns for making applications and their store and actions more composable.

I'd really like to hear what @acdlite thinks about this topic, though!

**Comment by gaearon** [comment]
>The outer component where the redux object is initialized is the one that knows these parameters.

```js
class Root {
  constructor(props) {
    this.actionCreators = makeMyActions('http://google.com');
  }

  render() {
    // you can do bindActionCreators(dispatch, this.actionCreators) here
  }
}
```

and if you need to update in response to prop changes, you can do so in `componentWillReceiveProps`.

**Comment by faassen** [comment]
With this approach is each time I want to use `bindActionCreators` I need to have access to `this.actionCreators`, even in nested components. I guess in the Redux pattern you pass action handlers along using props to nested components so this isn't an issue. Is that correct? Or would you run into trouble where you need to do this binding multiple times?

What I did in Flummox was instead of passing the action handlers down I'd wrap those components that needed to deal with actions in the `FluxComponent` component, so that they had access to the actions.

**Comment by gaearon** [comment]
I'd just pass the action creators down in this case. Mid-level "container" components would translate them to whatever props make sense for your dumb components.

**Comment by faassen** [comment]
But then I'm passing down action creators manually. Normally you don't need to do this - action creators are globals and Redux has special facilities so you don't need to manually pass down `dispatch` everywhere.

I suspect simply initializing the state with the starting URL is a nicer pattern here, but I have to do some experiments.

**Comment by gaearon** [comment]
Closing, please let me know if there's more to this than what we discussed so far.
