### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux#17]
Tests are sorely missing. Gonna try to fill that gap today.

**Comment by fibric** [comment]
what tools do you wanna use here?

**Comment by gaearon** [comment]
I'd probably use Mocha + `createShallowRenderer()` from React's TestUtils.

**Comment by emmenko** [comment]
I think at this point a basic testing environment is quite important. Makes refactoring safer...

**Comment by emmenko** [comment]
Should we close this?

**Comment by gaearon** [comment]
Yep! Great job.
