### ISSUE TITLE
Migration to Redux: listening to Firebase (or Socket.io) updates

### ISSUE THREAD

**Issue by clearjs** [gaearon/redux#170]
We rely on Firebase real-time data streaming, like this:
```js
componentWillMount: function() {
  firebase.child("profiles").child(props.user_id).on("value", this.onProfileChange);
},
componentWillUnmount: function() {
  firebase.child("profiles").child(props.user_id).off("value", this.onProfileChange);
},
```
This way, data is always in sync, and we only listen to the information we need.

With Redux, what would be the best way to listen to the data updates we're interested in? Here are the options I'm considering:
* Use async action creators for listening to updates and firing a series of actions. In this case, it is not clear how to unsubscribe from updates. Perhaps pass a subscription object to the action creator, and keep it in the component as well for unsubscribing?
* Write dedicated middleware that would handle special `SUBSCRIBE` / `UNSUBSCRIBE` actions and manage subscriptions in the app state? This seems to be a reasonable approach, and it could be combined with the previous option. What do you think?

I would be grateful for any comments, alternative approaches, code samples, etc.

**Comment by gaearon** [comment]
>In this case, it is not clear how to unsubscribe from updates

Can you clarify when you need to unsubscribe? Is using something like built-in `<Connector>` that stops listening on component unmount not enough?

**Comment by clearjs** [comment]
Unsubscribe on component unmount, just like in the example above. Yes, your idea to use `<Connector />` fits perfectly for this. Not sure I understand the whole picture yet, but that is a great hint to start. Thanks!

Also, what do you think about the two options I listed above?

**Comment by clearjs** [comment]
Actually, I'm confused now. `Connector` only stops listening to the store updates. But I need to unsubscribe from firebase updates as well.

**Comment by clearjs** [comment]
Closing the issue, since Dan's suggestion solves my problem elegantly. If anybody has further comments, they're certainly welcome.

**Comment by jkarttunen** [comment]
Just a quick note, good examples (or any examples) of firebase + redux seem to be pretty hard to find. It would be nice to have one at redux/examples

**Comment by gaearon** [comment]
Feel free to contribute :-)
