### ISSUE TITLE
Explore Swarm integration

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux#171]
[Swarm](https://github.com/gritzko/swarm) is a "replicated model" library.

I wonder if there is a potential to explore "eventually consistent" Flux action retranslation, and whether approaches similar to https://github.com/gaearon/redux/issues/113#issuecomment-114049804 can help here.

Sorry if I'm totally being nuts here.

(To clarify: this is meant to be done outside the core. #113 explains how to do something like that outside the core.)

**Comment by nbostrom** [comment]
You might want to have a look at Jet as well: http://jetbus.io/
Or if you want something more low level: https://github.com/dominictarr/scuttlebutt

**Comment by lapanoid** [comment]
Also look at http://pouchdb.com/, npm synchronization is based on it (couchdb actually). Works with no struggle in browser too.

**Comment by gaearon** [comment]
Nothing happening here, so closing. If somebody's up for it, let us know!

**Comment by Alex509** [comment]
I'd like to come up with a swarm redux TodoMVC example
Would it be of any interest?

**Comment by gaearon** [comment]
Sure (although probably in a separate repo).
