### ISSUE TITLE
Reducers (ex-'stores') must have a default return value for state to be initialized properly?

### ISSUE THREAD

**Issue by burmisov** [gaearon/redux#173]
Just spent some half an hour figuring this out.
Say I only had one action type to process in my reducer, so, based on my experience with 'vanilla flux', I did it like this:
```js
export default function myReducer (state = initialState, action) {
  switch (action.type) {
   case THE_ONE_ACTION_I_LISTEN_TO:
     return { ...state, ...someNewStuff };
  }
}
```
And (of course it's obvious to me now) I get an `undefined` state before the first action run, not the `initialState`. So I had to add the
```js
default: return state;
```
to correctly process the '@@INIT' action type. AFAIK that's nowhere to be found in the docs currently, guess it's just implied, but maybe mentioning it somewhere could save someone else a bit of time.

**Comment by gaearon** [comment]
Sorry for this.

I'd accept a PR checking that the return value of every store function inside `composeStores` is not `undefined`. This should cover the most common use case. Folks not using `composeStores` are assumed to know what they're doing anyway.

This will also need a test in `composeStores.spec.js`.

**Comment by gaearon** [comment]
(And they're going to be `composeReducers` in the next version... But we're not there yet ;-)

**Comment by gaearon** [comment]
Work in progress on fixing this: #174

**Comment by gaearon** [comment]
@burmisov Thoughts on #191?

**Comment by gaearon** [comment]
Superseded by #191.
