### ISSUE TITLE
moving subscribe to componentDidMount

### ISSUE THREAD

**Issue by mattybow** [gaearon/redux#178]
Hi, what do you think about moving the `subscribe` in the Connector's constructor into the componentDidMount method?

This way if you do any data fetching serverside, the views won't be subscribed to updates and `setState` won't get called which results in an error on the server because of the reconciler in React.

**Comment by gaearon** [comment]
I don't know much about server rendering. Is this more correct? Sure we can do that.

**Comment by mattybow** [comment]
NuclearJs does their mixin's [subscription](https://github.com/optimizely/nuclear-js/blob/master/src/create-react-mixin.js) in componentDidMount.  Since on the server we don't want the components to get their setState called I think this is the right place to put the `subscribe`

I'm not sure what the clean way to do this is, I think you would need to provide a reference to context.redux, like this:
```javascript
    constructor(props, context) {
      super(props, context);

      this.redux = context.redux;
      this.state = this.selectState(props, context);
    }

    componentDidMount() {
      this.unsubscribe = this.redux.subscribe(::this.handleChange);
    }
```

what do you think?

**Comment by emmenko** [comment]
Follow https://github.com/gaearon/redux/pull/179
