### ISSUE TITLE
React 0.12.x support?

### ISSUE THREAD

**Issue by lapanoid** [gaearon/redux#190]
Is it right that redux won't work with older react versions? Redux depend on es6 classes and inheritance, but in react 0.12.2 there is no React.Component from which you could inherit..

**Comment by gaearon** [comment]
Right now there are no plans to support earlier versions of React. What is the use case? 0.13 has been out for several months, 0.14 is on the way.

**Comment by johanneslumpe** [comment]
I feel that supporting older versions is something we shouldn't do. A project can always be updated to a new React version. It might come with some refactoring work, but if you want to replace something with redux, you're refactoring/migrating anyway, right?

**Comment by lapanoid** [comment]
Thanks for clarification!

**Comment by gaearon** [comment]
I think we can close this. I don't see a compelling reason to support 0.12 now that 0.14 is coming out soon.
