### ISSUE TITLE
.eslint config throws error when opening repo in Atom

### ISSUE THREAD

**Issue by damassi** [gaearon/redux#198]
I was browsing the latest 1.0 alpha just a moment ago and when I launched the project in Atom an error was thrown due to linter-eslint not being able to find `extends: eslint-config-airbnb` anywhere in my path.  Just a heads up; not sure if there's anything I can do to tell eslint to ignore extensions locally.

![screen shot 2015-06-30 at 10 55 59 pm](https://cloud.githubusercontent.com/assets/236943/8448357/37cfd150-1f7b-11e5-8bfe-2e69c2d1b3a2.png)

**Comment by jacobp100** [comment]
This can be fixed by the changing all the rules in the form

```
"react/jsx-uses-react": 2,
```

To

```
"react/jsx-uses-react": [2],
```

**Comment by gaearon** [comment]
Is this an atom bug? Is something wrong here?

**Comment by damassi** [comment]
I saw this as an unmet dependency issue with the repo, but looking fresh in the morning I see that `eslint-config-airbnb` is in package.json and so it is indeed an issue with Atom (or the plugin).  Will close and file issue there.  Thanks!

**Comment by zonak** [comment]
The exact same thing happens for me in **Sublime Text 3** with `SublimeLinter-contrib-eslint`.

**Comment by zonak** [comment]
Of we replace the `extends` value in `.eslintrc` with something like:

```
"extends": "./node_modules/eslint-config-airbnb/node_modules/airbnb-style/linters/.eslintrc"
```

everything works fine.
