### ISSUE TITLE
Find better decorator names

### ISSUE THREAD

**Issue by ooflorent** [gaearon/redux#20]
I liked previous decorator. While `container` is acceptable, `root` is too broad.
Maybe you (@gaearon) could rename `root` to `provides` or something similar.
Any thoughts?

**Comment by gaearon** [comment]
Provider / Container?

**Comment by gaearon** [comment]
If the issue is it looking weird in the `App` file, you can alias the import:

```js
import { root as reduxRoot } from 'redux';
```

`root` kinda makes sense in the context of Redux. I want to make it clear there's a single root in most applications, and that stores wouldn't work across different roots. Maybe it's obvious though.

**Comment by gaearon** [comment]
Let's rename `<Root>` (`@root`) to `<Dispatcher>` (`@dispatcher`).
Keep `<Container>` and `@container`.

Deal?

**Comment by ooflorent** [comment]
I like naming my decorators as _verbs_, similarly to what you did with `@performs` or `@provides`.
But `Dispatcher` and `dispatcher` are ok.

**Comment by gaearon** [comment]
Yeah.. I like verb decorators. But then I want them to map 1:1 to the components. And components as verbs seem bizarre.

**Comment by ooflorent** [comment]
While I agree on keeping noun for components, I think it is acceptable to
have decorators that are not 1:1.

-- 
Florent Cailhol

**Comment by gaearon** [comment]
More bikeshedding:

* `<Dispatcher>`, `@dispatcher`; `<Controller>`, `@controller`
* `<Dispatcher>`, `@dispatch`; `<Controller>`, `@control`
* `<Dispatcher>`, `@dispatcher`; `<Injector>`, `@injector`
* `<Dispatcher>`, `@dispatch`; `<Injector>`, `@inject`

Anything that you like?

**Comment by ooflorent** [comment]
I really like `@dispatch` and `@inject`

**Comment by bsansouci** [comment]
I second @ooflorent on this one. Inject seems to describe more what's happening under the hood than control is.

**Comment by gaearon** [comment]
What about `<Provider>`, `@provide`?
I like `@inject` but not very fond of `<Injector>`..

**Comment by gaearon** [comment]
Out in 0.7.0.
