### ISSUE TITLE
Help needed: port TodoMVC example to ES5 without magic

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux#203]
As @firstdoit validly observed on the Slack channel, a lot of Redux examples use bleeding edge features (destructuring, decorators, async/await) which can be a real bummer for beginners.

Here's a good thing you can help Redux with. Please take the example `todomvc` project in the `examples` folder, put it into a separate repository and port it fully to ES5.

**Comment by clearjs** [comment]
@gaearon This might be a good time to create a reduxjs organization (while it hasn't been taken). You can transfer redux there later.

**Comment by gaearon** [comment]
OK, I grabbed `reduxjs`.

**Comment by evankline** [comment]
@gaearon I'll add link here as soon as I finish porting @vramana's example to ES5.

**Comment by insin** [comment]
I've had a go at this: https://github.com/insin/redux-todomvc-es5/commit/ed15969b127e9adb65db3bea4b57c408586fa5d8

**Comment by evankline** [comment]
@insin looks good to me

**Comment by tsingson** [comment]
@insin   great, please push ahead.

**Comment by emmenko** [comment]
@clearjs great idea the org!

**Comment by clearjs** [comment]
The idea wasn't mine, it has been discussed earlier. I just wondered why it hasn't been taken yet.

**Comment by emmenko** [comment]
Oh, ok...regardless, it's a good idea :)

**Comment by Dakuan** [comment]
Not just beginners - also old timers who like to use what they know :older_man: :older_woman:

**Comment by badtant** [comment]
I'm looking for ES6 examples. Can only fint 5 or 7.

**Comment by gaearon** [comment]
@badtant If you backport the `examples` folder to use ES6, I'll merge. :-)

**Comment by insin** [comment]
Is it worth trying to automate some of this with https://www.npmjs.com/package/react-codemod?

**Comment by gaearon** [comment]
I'm closing because ES5 example is available at https://github.com/insin/redux-todomvc-es5 (thanks @insin!)

**Comment by mondwan** [comment]
Hi all,
It seems the example is too old for demonstrating migration with es5 plus redux nowaday?

There is no `Connector` anymore and I guess this is replaced by `connect()`.

Currently, I am switching between [es5 example][1] and [official example][2] and [tj frontend example][3]. However, I cannot link `Producer`, `Connect` and `MyApp`.

It throws error below

```
Could not find "store" in either the context or props of "Connect(MyApp)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(MyApp)"
```

Any suggestions :'( ?

[1]: https://github.com/insin/redux-todomvc-es5
[2]: http://rackt.org/redux/docs/basics/ExampleTodoList.html
[3]: https://github.com/tj/frontend-boilerplate

**Comment by insin** [comment]
I just merged a PR in the es5 example which brings it up to date with the redux 3.x API

**Comment by mondwan** [comment]
Thanks @insin
