### ISSUE TITLE
Remote time travel

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux#207]
The time travel devtools will soon be released.

During my talk, @DjebbZ suggested we make remote possible so one can write an IDE plugins (or browser extensions) that would embed time travel tools into the editor (Atom etc).

**Comment by taylorhakes** [comment]
That would be great. Here is an example of what Alt did in Chrome.

https://github.com/goatslacker/alt-devtool

**Comment by tsingson** [comment]
+1

**Comment by liamgriffiths** [comment]
Would love it as a chrome extension :dancer:

**Comment by gaearon** [comment]
@liamgriffiths https://github.com/gaearon/redux-devtools/issues/11

**Comment by resistdesign** [comment]
+4

**Comment by gaearon** [comment]
This seems to me like a specialized case of #313 so let's continue the discussion there.

**Comment by gaearon** [comment]
So, this exists now: https://github.com/zalmoxisus/remote-redux-devtools
For example, Atom plugin: https://github.com/zalmoxisus/atom-redux-devtools
