### ISSUE TITLE
Redux over the wire?

### ISSUE THREAD

**Issue by lapanoid** [gaearon/redux#211]
[This](http://codepen.io/elierotenberg/blog/flux-over-the-wire) is a great way of using flux on mobile, with web workers or whatever - splitting it on the client and server.
Could this be done in redux? This seems to me more magical as redux has stateless stores. Typically the simplest solution of this is to keep state in stores and stream stores changes to components which are located in other context.

**Comment by lapanoid** [comment]
As I understood from [middleware docs](https://github.com/gaearon/redux/blob/master/docs/middleware.md) it is pretty easy to intercept and even redirect actions.

So in this scheme direction from Component to Store Producer is manageable so I can log actions for example.

              +----------------> onChange ---------------+
              |                                                              v
Store Producer/Action Consumer             Store Consumer/Action Producer
      "SSoT" or "Dispatcher"                               "View" or "Component"
              ^                                                             |
              +---------------- onDispatch --------------+

But is that possible to intercept store changes in the same way?

**Comment by lapanoid** [comment]
I am looking for such configuration:

client reponsibility:
generate actions
consume store changes

server reponsibility:
generate store changes
consume actions

As I comprehand redux API only action generation is interceptable for now.

**Comment by lapanoid** [comment]
Figured out solution, thanks to @raydeo. 
redux has public methods subscribe/*get notified on new state*/,  dispatch, 
getState, which allows to

**Comment by lapanoid** [comment]
Here is [implemention](https://github.com/lapanoid/redux-remote) of this approach and [demo](http://lapanoid.github.io/redux-remote/)

**Comment by gaearon** [comment]
Let's continue this discussion in #313.
