### ISSUE TITLE
Possibly leaking DOM node references

### ISSUE THREAD

**Issue by kevinrobinson** [gaearon/redux#219]
I ran into this doing some profiling as part of https://github.com/kevinrobinson/redux/pull/1.  It looks like there's a DOM leak somewhere.

You can see the test case I'm using here on the counters app:

<img width="1242" alt="screen shot 2015-07-05 at 10 00 23 pm" src="https://cloud.githubusercontent.com/assets/1056957/8514611/46c8eb94-2361-11e5-9830-e80d1dfebe05.png">

This might not matter much in real applications, and I'm not quite sure how to investigate further.  I tried seeing if I could find more in the profiling tools but didn't get anywhere yet.  I also read through the code to see if anything stuck out but couldn't see anything there either.

Maybe someone else knows more about profiling this, or can track it down?

**Comment by acdlite** [comment]
Damn, if that's true where the hell is it happening? The only possible candidates I can think of is Connector (which looks to be unsubscribing correctly on unmount) or the Redux class. Everything else is a pure function!

Oh, could you try testing on this branch: https://github.com/gaearon/redux/tree/breaking-changes-1.0? The dispatcher has been removed and the Redux/Store class has been cleaned up considerably. Maybe the leak has already been plugged.

**Comment by acdlite** [comment]
Actually if the leak is related to DOM nodes then I can't imagine how it would be related to Redux...

**Comment by kevinrobinson** [comment]
@acdlite Yeah I'm stumped at the moment too.  One thought was that perhaps the GC cycle is just longer for DOM nodes and it hadn't kicked in yet?  That's just a straight guess though.

**Comment by kevinrobinson** [comment]
@acdlite Not sure, ran into this.

<img width="654" alt="screen shot 2015-07-05 at 10 19 38 pm" src="https://cloud.githubusercontent.com/assets/1056957/8514743/fa67dae6-2363-11e5-8c5e-46c018ab7ad3.png">

Also since I've seen you online but don't think we've ever chatted, you're doing awesome work!  :)

**Comment by acdlite** [comment]
@kevinrobinson Same to you!

**Comment by gaearon** [comment]
Closing in favor of https://github.com/gaearon/react-redux/issues/3.
