### ISSUE TITLE
State that doesn't fit into memory

### ISSUE THREAD

**Issue by andersekdahl** [gaearon/redux#222]
First off, there are some great ideas in this library, and I very muched enjoyed your talk at React Europe!

A lot of Flux or Flux-like libraries focus on use cases where all state fits in memory, and never mentions how you would tackle use cases where you use WebSQL or IndexedDB to store state and only fect a subset of it on demand. If your stores implement getters, it's simple to put the on-demand queries there. But where do you put it with Redux?

Let's say you have a todo app, but the number of todos are too big to have in memory. How would you approach that with Redux?

**Comment by johanneslumpe** [comment]
You could implement a simple pagination. Then to fetch more data you'd just call an action which in turns fetches the data from your database backend. The new data gets passed to your reducers and updates the state.

It's not different from a normal async request I'd say. Except that you don't use a REST api or something, but a local database.

**Comment by andersekdahl** [comment]
I agree that it's conceptually the same as going over the wire to fetch data, but it's often assumed that you fetch everything once and have everything in memory after that.

Do you have an example to point at for pagination? And perhaps filtering of finished todos where the filtering isn't done on an array but having the backend/database do it.

**Comment by andersekdahl** [comment]
I'm not looking for a silver bullet here. Handicaping the client by not letting it know everything about state management puts some tough constraints on it. Was just looking to see what your take it on it was.

**Comment by andersekdahl** [comment]
(That is, when the server keeps state the client doesn't have. Different story with a client database with all state.)

**Comment by johanneslumpe** [comment]
Sorry, I currently have no example :/ But pagination would just be the same as with a web api. You only need to know the total count, the current page you're on and the amount of items per page. Then you can easily construct a working pagination. (Without having to store anything in memory, each page could just be fetched from the db).

Filtering would work the same, maybe something like this:

```javascript
const action = {
  filterItemsByKeyword: (keyword) => {
    return (dispatch, getState) => {
      // you could also just pass in the current page into the action
      const { currentPage } = getState().todos.pagination;
      
      // whether the db is local or remote really does not matter
      api.retrieveItemsFilteredByKeyword(keyword, currentPage)
        .then(results => dispatch({type: ITEMS_FETCHED, payload: results}));
    };
  }
}
```

Does that help you?

**Comment by andersekdahl** [comment]
I think it does, thanks! I suspect that I'm approaching this with a different mindset than I should. I'll play with it, and reopen if I find something interesting.

**Comment by johanneslumpe** [comment]
:+1:
