### ISSUE TITLE
Warn or Error when no store listeners

### ISSUE THREAD

**Issue by taylorhakes** [gaearon/redux#225]
While debugging this #208, I noticed there weren't any store listeners. https://github.com/gaearon/redux/blob/breaking-changes-1.0/src/Store.js#L33 . 

I thought it would be helpful for a warning or error if listeners length is 0. This doesn't have to be a bug, it could be because user hasn't used any `<Connector>` or `@connect` decorators. Would this be helpful? Or are there valid use cases for not having listeners?

**Comment by gaearon** [comment]
I think it's a valid use case when doing server rendering.

**Comment by taylorhakes** [comment]
On the server side, redux does not dispatch events, so that code would not be hit. The state is put in the components and rendered into a string. I am fine keeping this closed if you don't think it would not be helpful.

**Comment by gaearon** [comment]
>On the server side, redux does not dispatch events

You'll want to dispatch on server if you preload data before rendering. Most universal examples we link to in README do that.

**Comment by taylorhakes** [comment]
Ok, got it. Sorry about that. I was doing it differently in past.
