### ISSUE TITLE
Possibility use Redux without React

### ISSUE THREAD

**Issue by xgrommx** [gaearon/redux#228]
Hello everyone. How can I use Redux without React? For example angular, vue or just a pure virtual dom?

**Comment by acdlite** [comment]
```js
`store.subscribe()` // Register a listener which is called on every state change. Returns unsubscribe.
`store.dispatch()`// Dispatch an action
`store.getState()`// Get the current state of the store
```

That's really all there is to it. It may help to check out the source for Provider and Connector to see how they interact with the store (currently called the Redux instance, before 1.0).

**Comment by acdlite** [comment]
By the way, middleware and higher-order stores are not React specific, so they will continue to work.

**Comment by xgrommx** [comment]
@acdlite Hmm.. will be better provide a small example like a counter

**Comment by acdlite** [comment]
@xgrommx I agree. Which library do you think would be most helpful to create an example for?

By the way I like your Rx book! Have you seen [redux-rx](https://github.com/acdlite/redux-rx) yet? That may be a good integration point for certain libraries.

**Comment by xgrommx** [comment]
@acdlite Sure! I look at redux-rx but I don't understand how can I use it with React or something. Will be better if you show me example with React and angular

**Comment by acdlite** [comment]
Alright, I'm no Angular expert but perhaps we can find a volunteer to port the TodoApp.

**Comment by xgrommx** [comment]
@acdlite But maybe you can provide example for React?

**Comment by acdlite** [comment]
Oh you mean of redux-rx? Sure will, I have that on my todo list.

**Comment by xgrommx** [comment]
@acdlite Maybe I don't understand how to working Redux in deep. I could be to port todo to angular but I need example with React.

**Comment by xgrommx** [comment]
@acdlite Exactly! I need example with redux-rx with React. Also it will be similar for redux-transduce.

**Comment by xgrommx** [comment]
@acdlite Exist examples with refluxjs https://github.com/spoike/refluxjs/issues/66 and https://github.com/javamonn/Angular-TodoMVC-Redux/blob/master/app/services/TodoStore.service.js maybe these examples to help.

**Comment by gdi2290** [comment]
I'm creating the Angular 2 version of the counter example now

**Comment by gdi2290** [comment]
I have the angular 2 example for counter https://github.com/gaearon/redux/pull/232

**Comment by yang-wei** [comment]
I implement Redux with Vue.js and you can see it [here](https://github.com/yang-wei/vue-flux).

Need feedback if this is the right way to use Redux on other non react app.

If everything is ok I send a pull request of TodoMVC implemented by vuejs + redux.

**Comment by wbuchwalter** [comment]
I started working on [ng-redux](https://github.com/wbuchwalter/ng-redux) which helps you connect angular and redux together.
An example of usage can be found here [tsRedux](https://github.com/wbuchwalter/tsRedux) (in TypeScript).

**Comment by gaearon** [comment]
I'm closing, as the new docs strongly suggest in several places that Redux is not tied to React.
The new docs also document Store API in great detail.

**Comment by dd1994** [comment]
https://github.com/reactjs/redux/blob/master/examples/counter-vanilla/index.html

**Comment by Fallenstedt** [comment]
I have made a Medium post that shows how to set up and use Redux without React. You can read it here: https://medium.com/@Fallenstedt/how-to-make-state-management-suck-less-with-redux-f5585edffe5
