### ISSUE TITLE
Multiple stores in 1.0 alpha

### ISSUE THREAD

**Issue by jptaylor** [gaearon/redux#237]
Is there a way to pass more than one store to a `Provider` ?

```
const storeone = createStore(formStore, PersonalDetailsAPI);
const storetwo = createStore(formStore, FinancialsAPI);

render() {
    return (
      <Provider store={???}>
        {this.renderRoutes.bind(this)}
      </Provider>
    );
  }
```

I tried using `composeReducers` and passing in the two stores, but no such luck. Curious to know what the intended API is going to be for multiple stores.

**Comment by ooflorent** [comment]
Why do you need multiple stores? Sorry, I don't get the use case.
Can you elaborate a bit more what you are trying to achieve?

**Comment by jptaylor** [comment]
@ooflorent I have a series of forms that are posting data to individuals APIs. My intention was to have a store for each form (each form residing on its own route) and pass in different initial data to give the form its state.

So, series of routes, each containing a form that posts data to different API endpoint.

**Comment by ooflorent** [comment]
You don't need multiple stores to achieve that but multiple reducers.

```js
// reducers.js
export step1 from './step1'
export step2 from './step2'

// constants.js
export const STEP1_COMPLETED = 'STEP1_COMPLETED'
export const STEP2_COMPLETED = 'STEP2_COMPLETED'

// step1.js
import { STEP1_COMPLETED } from './constants'

const initialStep1State = {
  email: '',
  password: '',
}

export function step1(state = initialStep1State, action) {
  switch (action.type) {
    case STEP1_COMPLETED:
      return { ...state, email: action.email }

    default:
      return state
  }
}

// step2.js
import { STEP2_COMPLETED } from './constants'

const initialStep2State = {
  firstname: '',
  lastname: '',
}

export function step2(state = initialStep2State, action) {
  switch (action.type) {
    case STEP2_COMPLETED:
      return { ...state, firstname: action.firstname, lastname: action.lastname }

    default:
      return state
  }
}

// actions.js
import post from 'some-networking-lib'
import { STEP1_COMPLETED, STEP2_COMPLETED } from './constants'

export function saveStep1(data) {
  return (dispatch) => {
    post('/step1', data).then(({ email }) => {
      dispatch({ type: STEP1_COMPLETED, email })
    })
  }
}

export function saveStep1(data) {
  return (dispatch) => {
    post('/step2', data).then(({ firstname, lastname }) => {
      dispatch({ type: STEP2_COMPLETED, firstname, lastname })
    })
  }
}

// App.js
import { createStore, applyMiddleware } from 'redux';
import { Provider } from 'redux/react';
import * as reducers from './reducers';

const createStoreWithMiddleware = applyMiddleware()(createStore);
const store = createStoreWithMiddleware(reducers);

export default class App {
  render() {
    return (
      <Provider store={ store }>
        { () => <FormWithStepsApp /> }
      </Provider>
    );
  }
}
```

Then each form only selects what it needs:

```js
@connect((state) => ({
  step1: state.step1
}))
```

**Comment by jptaylor** [comment]
I see, sorry for the ignorance. Thanks very much @ooflorent.

**Comment by ooflorent** [comment]
No problem!

**Comment by jptaylor** [comment]
@ooflorent out of interest, is there a way to use the same reducer with different initial data? My reducer looks like this: 

```
export default function account(state, action) {
  switch(action.type){

    case constants.FORM_VALUE_UPDATE:
      return Object.assign({}, state, {
        fields: {
          ...state.fields,
          [action.name]: action.data
        },
        progress: calculateProgress(state.fields)
      });

    case constants.FORM_SUBMIT:
      return { ...state, pending: true };

    case constants.FORM_SUBMIT_ERROR:
      return { ...state, errors: action.errors, pending: false };

    case constants.FORM_SUBMIT_SUCCESS:
      return { ...state, errors: [], pending: false };

    default:
      return { ...state, progress: calculateProgress(state.fields)};
  }
}
```

Only thing that changes is the initial data for each form. Any ideas?

**Comment by ooflorent** [comment]
You can wrap your stores using functions:

```js
function account(state, action) {
  // ...
}

export const function account1(state = initialState1, action) {
  return account(state, action)
}

export const function account2(state = initialState2, action) {
  return account(state, action)
}
```

**Comment by jptaylor** [comment]
@ooflorent thanks kindly.

**Comment by emmenko** [comment]
@jptaylor we are working on documentation, we can have a look here in the meantime https://github.com/gaearon/redux/pull/140

**Comment by ConAntonakos** [comment]
Sorry for reviving this old issue, but I had a similar concern, i.e., using Redux with isolated forms as @jptaylor described. Would the approach be that you treat reducers as separate stores? Can you break down your application to store separate logic from separate views, and does that all go into one global store scope? Does Redux essentially act as a global store for your entire application? Sorry for my ignorance as well! Still trying to figure out how to integrate Redux/Flux and how it fits.

**Comment by gaearon** [comment]
I think StackOverflow would be a more appropriate place to ask this, as the answer wouldn’t get lost there. Would you mind asking it there, preferably in a more specific way (say, with a code example), and dropping a link here?

**Comment by ConAntonakos** [comment]
Yes, absolutely! Thanks for your response, @gaearon.
