### ISSUE TITLE
eslint error on return class

### ISSUE THREAD

**Issue by mikekidder** [gaearon/redux#24]
Currently showing an eslint error in the decorators, although Babel seems to work it out fine.

If **/src/addons/root.js** was changed to:

```javascript
export default function root(stores) {
  return DecoratedComponent => {
    class ReduxRootDecorator {
      static displayName = `ReduxRoot(${getDisplayName(DecoratedComponent)})`;

      render() {
        return (
          <Root stores={stores}>
            {props => <DecoratedComponent {...this.props} {...props} />}
          </Root>
        );
      }
    }
    return ReduxRootDecorator;
  };
}
```

No eslint errors, babel will assign the IIFE to var, and return it after the class block.

Good idea?  Not sure if this is bug with eslint, or an example where you shouldn't return a class due to hoisting.

**Comment by ooflorent** [comment]
There is no hoisting with classes. Adding `babel-eslint` should mute the warnings.

**Comment by gaearon** [comment]
Could be a babel-eslint bug. To clarify, here's what I see:

![screen shot 2015-06-03 at 23 07 26](https://cloud.githubusercontent.com/assets/810438/7970245/580d8110-0a45-11e5-8311-7f8ba0c138c5.png)

@hzoo any ideas?

**Comment by gaearon** [comment]
I'm closing since it's not really an issue in Redux.

**Comment by hzoo** [comment]
Yeah will take a look.

**Comment by hzoo** [comment]
@gaearon It's because I was visiting the class.id which I don't need to do.

However the default eslint will also error with `no-unused-vars` on a class. ESLint did made an exception for exports.

**Comment by gaearon** [comment]
Thanks! :+1:

**Comment by hzoo** [comment]
Ok should be fixed in 3.1.11

**Comment by mikekidder** [comment]
Confirmed working now on Atom editor w/3.1.11.  Woot!

**Comment by gaearon** [comment]
:+1: Thank you @hzoo!
