### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by xgrommx** [gaearon/redux#241]
When I cloned repo I cannot run npm install on Windows.

**Comment by gaearon** [comment]
Yes, we should fix this. One way is https://github.com/gaearon/redux/pull/94. Another way is to go back to writing commands inline in `package.json`. I've been busy with other stuff so I'm not sure which option is better. What do you think?

**Comment by xgrommx** [comment]
@gaearon Maybe this article can help you http://shapeshed.com/writing-cross-platform-node

**Comment by xgrommx** [comment]
Also interesting this repo https://github.com/kimmobrunfeldt/concurrently and example how can be usable https://github.com/RickWong/react-isomorphic-starterkit/blob/master/package.json#L25

**Comment by gaearon** [comment]
This will be fixed by #267. Let's track it instead.

**Comment by gaearon** [comment]
#267 is merged into `breaking-changes-1.0` branch, feel free to give it a go.

**Comment by urivasas** [comment]
this did not seem to fix the issue. removing prepublish from package.json seems to fix the problem. please consider re-opening. thanks.

**Comment by gaearon** [comment]
@recfish Can you give details? This is a very vague error report. Without the exact error there's nothing I can do to fix it.
