### ISSUE TITLE
Immutable library

### ISSUE THREAD

**Issue by dominicglenn** [gaearon/redux#243]
When doing a project using redux, would it be useful to use an immutability library to ensure that the stores never ever modify the state that they are passed, or would this be overkill and just make it more cumbersome to access store data inside the components and the state selector?

I'm curious as it seems it would be easy to mutate the state accidentally inside the stores and redux makes hard assumptions that they are not mutated?

Cheers

**Comment by gaearon** [comment]
You can use ImmutableJS, mori or any other immutable library of your choice.

We don't want to be prescriptive—if you're fine with using them, please do!
It'll be easier to avoid accidental mutations.
