### ISSUE TITLE
The dispatcher doesn't fire in this scenario

### ISSUE THREAD

**Issue by volkanunsal** [gaearon/redux#261]
I have a complicated use case. My component needs to render another component on a part of the page that is not managed by React. And this component needs to be able to all the actions it receives, obviously. To do that, I have created the following –– let's see if you can follow this:

```js
export default class MapContainer {
  render() {
    return (
      <Provider redux={redux}>
        {() => <Map />}
      </Provider>
    );
  }
}

```

```js
@connect(state => state)
export default class Map {
  render(){
    let { dispatch } = this.props;
    let { context: { redux: { getState }}} = this;
    let {MapReducer: state} = getState();

    return (<NewMap
          name={ state.name }
          options={ state.options }
          layers={ state.layers }
          controls={ state.controls }
          redux={ this.context.redux }
        /> )
  }
}
```

```js
export default class NewMap {

  _renderComponent({component}){
    // Ensure the mounted component can receive data from Redux.
    var ComponentFactory = React.createFactory(ComponentWrapper);
    let {elementClass, actions, props} = component;
    return <Provider redux={this.props.redux}>{()=> ComponentFactory({elementClass, actions, ...props})}</Provider>;
  }

  renderControl(){
    let provider = this._renderComponent(component);
    React.render(provider, element.getContainer());
  }

  render(){
    // render the map
  }
}
```

```js
@connect(state => state)
export default class ComponentWrapper {
  render() {
    let { dispatch, ...rest } = this.props;
    let actions = bindActionCreators(this.props.actions, dispatch);
    var ElementFactory = React.createFactory(this.props.elementClass);
    return ElementFactory({ actions, ...rest });
  }
}
```

This is really ugly and complicated, but it works up to a point. It breaks down when the user clicks on the links connected to the actions on the component rendered by the first component. I checked the actions and can confirm that they are getting called, but the dispatcher is not firing –– maybe it's not wrapped around the actions that get passed to the component? I can't think of any other reason.

What might be going on here? 

(Btw, the Provider/Connector API is way too complicated. I'm glad you folks are looking into that.)

**Comment by gaearon** [comment]
Please try on 1.0 RC.
This is probably one of the bugs we fixed there.

https://github.com/gaearon/redux/releases/tag/v1.0.0-rc

**Comment by volkanunsal** [comment]
Just upgraded. I don't see any difference. The dispatcher isn't firing.

**Comment by volkanunsal** [comment]
I'm going to try to reproduce it...stay tuned.

**Comment by gaearon** [comment]
Please add a failing test if you can extract one.

**Comment by volkanunsal** [comment]
I think I managed to fix it. I don't exactly how, but it started working. The gist of it was at some point in the process, the actions were not getting bound to the dispatcher. It was very difficult to debug this because the returned object looked exactly the same as it had without bindings. 

So, one small suggestion is perhaps to make this easier on the users by changing the return type of this function that reflects the fact that the original functions have been wrapped by a closure. 

Something like:

```
actions => boundActions
```

**Comment by gaearon** [comment]
Hmm. We can't really do anything with pure action creators because we don't wrap them.
