### ISSUE TITLE
Runtime type checking

### ISSUE THREAD

**Issue by volkanunsal** [gaearon/redux#268]
What do you guys think about adding a type system to some of the endpoints...? 

The [tcomb](https://github.com/gcanti/tcomb) project is a very cool runtime type checking system similar to flow. It might make it easier to reason about the flow of the code.

**Comment by gaearon** [comment]
We're adding Flow: https://github.com/gaearon/redux/pull/254
Does this help? It's not runtime but will help doc-wise.

**Comment by volkanunsal** [comment]
Yeah, compile-time is safer than runtime checks anyways.

**Comment by hzoo** [comment]
Can try out https://github.com/babel-plugins/babel-plugin-flow-comments as well now
