### ISSUE TITLE
1.0.0-rc example can not run!

### ISSUE THREAD

**Issue by colinshen** [gaearon/redux#270]
the problem is that can not import redux in my project, this caused an error can not find module. so,i tried to run the todomvc example. I got same problem.  I did that on windows(didn't try it on other platforms)

**Comment by gaearon** [comment]
Can you please paste the specific error you get?

**Comment by colinshen** [comment]
![qq 20150715203944](https://cloud.githubusercontent.com/assets/5463041/8698527/a6438a0c-2b31-11e5-99d5-d3d5eaeadf23.png)
here is the error from the todomvc example！
  "dependencies": {
    "classnames": "^2.1.2",
    "react": "^0.13.3",
    "react-redux": "^0.2.1",
    "react-router": "^1.0.0-beta3",
    "redux": "^1.0.0-rc"
  },
  "devDependencies": {
    "babel-core": "^5.6.18",
    "babel-loader": "^5.1.4",
    "node-libs-browser": "^0.5.2",
    "raw-loader": "^0.5.1",
    "react-hot-loader": "^1.2.7",
    "style-loader": "^0.12.3",
    "todomvc-app-css": "^2.0.1",
    "webpack": "^1.9.11",
    "webpack-dev-server": "^1.9.0"
  }
}
i did not change anything

**Comment by gaearon** [comment]
If you copied examples as is, you need to remove some lines from `webpack.config.js` that alias `redux` to the `src` folder. This is only done so you can play with the source directly: in a separate project there is no such directory.

**Comment by gaearon** [comment]
We'll make it clearer (working on it as we speak).
In the meantime just remove

```js
    alias: {
      'redux': path.join(__dirname, '..', '..', 'src')
    },
```

and later

```js
, {
      test: /\.js$/,
      loaders: ['babel'],
      include: path.join(__dirname, '..', '..', 'src')
    }
```

from `webpack.config.js` and it will work.

**Comment by casio** [comment]
.. that will compile. But also lead (onclick '+' in the counter example) to:
    
    Uncaught TypeError: dispatch is not a function (bindActionCreators.js:15)

Seen in branch breaking-changes-1.0 & also in master where the above change isnt necessary to compile

**Comment by gaearon** [comment]
@casio This is due to a Babel bug: https://github.com/babel/babel/issues/2094.

**Comment by gaearon** [comment]
Closing because this is now reflected in the docs: ccbffe27f7f6e92e2a6752df7cc51563ea2278e1.

**Comment by jmarceli** [comment]
Just to clarify Babel bug is not issue anymore. Everything should work. I get same error due to double `export default ...` directive inside my custom React Component.
