### ISSUE TITLE
Do we need a new tagline?

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux#273]
“Atomic Flux with hot reloading” was enough to spark interest but is there a better way we can position ourselves now?

What I believe to be key ideas of Redux:

* **Ecosystem for great developer experience**. Hot reloading, [devtools with replay of actions as you change the code, time travel and error handling](https://github.com/gaearon/redux-devtools), [dev session persistence](https://github.com/gaearon/redux-devtools/blob/master/src/persistState.js), crash reporting are all easy to do outside the core.

* **Contracts over privileged APIs**. If you look at [1.0 branch](https://github.com/gaearon/redux/tree/breaking-changes-1.0/src), there isn't really much [API surface](www.youtube.com/watch?v=4anAwXYqLG8). We're not doing [modularity for modularity's sake](http://jlongster.com/Modularity). It just so happens that not locking people into a particular APIs and instead suggesting to implement contracts (e.g. a reducer contract) has many benefits: people are able to migrate to (and from) Redux easily by building small adaptors (e.g. a `ReducerStore` for Flux library they're using). This also lets us have a bigger interoperable ecosystem, as even the [devtools for Redux](https://github.com/gaearon/redux-devtools) can be adapted to work with other Flux frameworks.

* **Only concerned with managing state mutation.** Redux doesn't care *what* you use for state (plain objects, ImmutableJS, Mori), it doesn't care *what* you use for updating the views ([React](github.com/gaearon/react-redux), [Angular](https://github.com/gaearon/redux/pull/232)), it also doesn't care how you orchestrate async (e.g. [Rx](https://github.com/acdlite/redux-rx)).

What do you think? Is there a better tagline for Redux 1.0?

**Comment by bananaoomarang** [comment]
"Reduce, Reuse, Redux: Uni-directional flow for the functionally minded"

**Comment by arstin** [comment]
"Reducing the headache of managing state."

Which could be followed by a list of ways it does this (simple unidirectional data flow, dev tools, extensibility supported by a rich ecosystem, stack interoperability).

**Comment by bfitch** [comment]
"Complex state management for humans"

**Comment by bfitch** [comment]
"A design pattern for observing and changing application behavior instantly"

**Comment by insin** [comment]
"Redux: Elm update for humans" :grinning:

**Comment by rseymour** [comment]
Reduce your cognitive overhead

**Comment by gaearon** [comment]
https://twitter.com/andrestaltz/status/621343164352327680
https://twitter.com/en_js/status/621350082516901889

kind of contradictory but I like both..

**Comment by taylorhakes** [comment]
"Functional Flux", "Higher-order Flux",  "Transparent Flux"

**Comment by acdlite** [comment]
Unadulterated Flux :dancer: :dancer: :dancer:

**Comment by kurtharriger** [comment]
I like the Reduce, Reuse, Reflux.

Im not sure why facebook called there thing flux, but if makes me think of the flux capacitor in back to the future which is kinda cool since Reflux makes time travel possible.  

How about Reduce, Reuse, Reflux: Developing faster with time travel.

**Comment by hugobessaa** [comment]
"Unidirectional data commander: improves your component fleet"

I think we should avoid time-travel related taglines, as Redux is much more than just time-traveling

**Comment by dherault** [comment]
"Redux : functional Flux library allowing simpler state management and great developer experience."

**Comment by mindjuice** [comment]
Redux = Reduce + Reload + Replay + Flux

**Comment by gaearon** [comment]
“Predictable state management for JavaScript apps.”

**Comment by gaearon** [comment]
I'm satisfied with https://github.com/gaearon/redux/issues/273#issuecomment-123735649.
