### ISSUE TITLE
How to implement an extensible app using Redux?

### ISSUE THREAD

**Issue by anatoliyarkhipov** [gaearon/redux#277]
Maybe this question generally about Flux, not Redux, but I would like to see an example on Redux.

By "extensible" I mean something like the next example:

Imagine that we have some basic app which displays a grid with data. Click on a row in this grid runs the "select" action. And reducer, which responsible to process this action, marks the clicked row as selected (and the grid component adds some class to the row, e.g. `selected`).

And now we want to implement some module. It's a viewer, which will be displayed at the right side of the grid. And this viewer will display the selected record. But we must to load details of the record, because viewer needs some additional data which not displayed in the grid.

The question: at what moment and where should I load details of the record? Without changing the original app code. In other words: how to make the original app code extensible for this purpose?

I have three possible solutions, but I feel like that there is something wrong with all of this:

* Events. E.g. the "select" action fires the `selectionChange` event, and any modules can listen for it and run its own actions like `fetchDetails`. 

```
registerHandler('selectionChanged', (data) => {
    
    ModuleActions.fetchDetails(data.id)
})
```

* A registry. We can implement some registry of actions, and decorate the original `select` action with a custom action, which will run the `fetchDetails` after the original select:

```
// Somewhere in the app initialization code

registry.add('select`, () => /* Some original action */ }

// Somewhere in the module initialization code

registry.decorate('select', original => {

    return (data) => (dispatch) => {
        
        // Call the original select action
        original(data)
        
        // The custom behavior
        ModuleActions.fetchDetails(data.id)
    }    
})
```

* Some "Smart" viewer component watches for the selected record in the app state and run the `fetchDetails` action when it's changed.

```
// ...
componentWillReceiveProps({ selected }) {
    
    if (selected != this.state.selected) {

        this.setState({ selected })

        ModuleActions.fetchDetails(selected.id)
    }
}
```

What you think about that?

**Comment by gaearon** [comment]
I'd leave it to a component. A component on the right side listens to changes in `selected` item and maybe fires some relevant (but unrelated) actions in `componentWillReceiveProps` similar to how you described it in the last paragraph.

**Comment by anatoliyarkhipov** [comment]
Thanks, @gaeron!

I have more examples to discuss, but I'm a little busy now. I'm planning to add them in the end of the next week. Can you do not close the issue, please?

**Comment by gaearon** [comment]
Can you just open new issues? It's easier to discuss & search them later if each issue is focused around a single specific problem or question.

**Comment by anatoliyarkhipov** [comment]
Okay, no problem, I think it makes sense.
