### ISSUE TITLE
Where do I put code to make calls to server?

### ISSUE THREAD

**Issue by DJCordhose** [gaearon/redux#281]
If action creators and stores are pure functions, where do I make calls to a server? For loading or storing data. I have seen this in action creators in other flux implementations.

**Comment by emmenko** [comment]
Still in the action creators. But _instead of returning a plain object_, you **return a function** that accepts `dispatch` as argument, which you can use to dispatch your action asynchronously.

You can [have a look here](https://github.com/gaearon/redux/blob/improve-docs/docs/faq.md#how-do-i-do-async).

PS: be aware that to make this work you have to use the [`thunk` middleware](https://github.com/gaearon/redux-thunk) to enable async dispatches.

**Comment by rrag** [comment]
Is it recommended to call `dispatch` more than once from action creator?

like so

```
export function searchSomethingWhichTakesALongTime(query) {
  return dispatch => {
    dispatch(showLoadingSpinner()); // dispatch 1
    $.ajax(...)
    .done(function() {
      dispatch(doStuff()); // dispatch 2
    });
  };
}
```

**Comment by gaearon** [comment]
Sure, that's exactly what the thunk form is for!

**Comment by DJCordhose** [comment]
Thanks all, that answers it :+1:
