### ISSUE TITLE
dispatch action from store?

### ISSUE THREAD

**Issue by badtant** [gaearon/redux#284]
So, I have a data store that holds data from a server call. I also have a meta store that hold data for the entire app (page title and such).
Depending on the server call I want to update the meta store. If the call fails or if it's success I want to despatch an action to the meta store and update depending on the data I get from the server.

What is the best way to do this? Should my data store dispatch the meta action or should I have my meta store listen to the success/fail actions for the data store?

**Comment by gaearon** [comment]
Stores (to be renamed “reducers” in 1.0) are pure functions and can never dispatch actions.

>should I have my meta store listen to the success/fail actions for the data store?

This sounds right.
