### ISSUE TITLE
Exceptions are swallowed by the store

### ISSUE THREAD

**Issue by wereHamster** [gaearon/redux#285]
If a reducer throws an exception it is swallowed deep inside redux, and not even logged to the developer console.

**Comment by taylorhakes** [comment]
Are you using a promise middleware? Redux doesn't swallow any errors by itself. Can you post a code snippet to reproduce the issue?

**Comment by gaearon** [comment]
I'm pretty sure we're not swallowing exceptions.
In fact we don't even have try-catch statements in the source.

I'm closing but feel free to share the details of what was happening!

**Comment by wereHamster** [comment]
It ended up being React that caught the exceptions. Probably.
