### ISSUE TITLE
[React-Native] How to use redux in react-native?

### ISSUE THREAD

**Issue by soliury** [gaearon/redux#293]
I have used the redux in a react-native app---[noder](https://github.com/soliury/noder-react-native), But I have some problems:

* Is there can be two connectors in a redux app?

* I put the Navigator in the connector, is this a  good way?

* Is there any react-native Example code for use redux, I mean I know how to use, but I don't know this is the best way.

* Look into my [noder](https://github.com/soliury/noder-react-native) , component nest component, and the state is passed through many component, I think this will result in some Performance issues especially in react-native. Can you give me  some advice?

**Comment by gaearon** [comment]
You can use as many Connectors as you need. You can even nest them, although it is advisable that you only use them at top level and pass the data further down as props.

If you have performance issues you can implement `shouldComponentUpdate` on some of your components (you can use `react-pure-render` package). Don't bother until you *actually* have performance issues though. :-)

Finally for optimizing selecting state from Redux store you can use reselect: https://github.com/faassen/reselect

I looked at your code and it seems to use Redux correctly.

**Comment by soliury** [comment]
OK, I see. Thank you advice. 

If nest connectors, will it cause performance issues?

**Comment by gaearon** [comment]
No, but it will make your app more complex because there are several points where data may change.

It's better to use React's model (pass data via props) wherever possible.

**Comment by soliury** [comment]
Now I have a problem. 

I have two components(Topic and Comments) which should communicate each other. In Topic component it have a place to show how many comments , and then I push to Comments component, I create new reply, the comments count should update in Comments component.  So I am confused should I use the connenctor there ? Or just let the Topic pass a callback to Comments?

**Comment by gaearon** [comment]
Is Comments inside Topic?

If so, put Topic inside connector and bind addComment action creator there. Grab comment list from connector and pass it to Comments.

**Comment by soliury** [comment]
No, the Comments and Topic both are a scene in Navigator...

**Comment by soliury** [comment]
But in react-native, when push a scene from one to another, it won't unMount the first one.

I mean, firs I am in Topic component, and then I push the Comments component, the Topic component will not umMount. It will exist until the Topic scenc have been poped.

**Comment by gaearon** [comment]
Oh okay. So they're not children, but siblings.

In this case it's probably easiest to wrap both in `<Connector>`? Or do they have a shared parent you can wrap in `<Connector>`?

**Comment by soliury** [comment]
They have a shared parent call Navigation.

But there will have another problem, a Navigator have many scencs, it may have two topic and two comments. If wrap in Connector, four components is in the Navigator...... But then should not have the same data.

**Comment by gaearon** [comment]
You can wrap every screen into a Connector. That should solve your problem.

**Comment by soliury** [comment]
Ok, thank you very much.
