### ISSUE TITLE
How do I get the dispatcher instance for a store? Or am I missing something?

### ISSUE THREAD

**Issue by StevenLangbroek** [gaearon/redux#298]
I've made a decorator that fetches resources when a component is mounted, which is working lovely, but now I have the following scenario:

On app start, we need to load locales, before anything else happens basically. I've added a "store" with reducers for merging the i18n data in, i'm using the `@provide(store)` decorator, but I'm a bit lost as to where to call my action `fetchLocales()` from... I don't want to add another layer of components, but to bind the actionCreators (`bindActions(localeActions, dispatch)`) I need access to the dispatcher, which is only available after using the `connect` decorator... Am I missing something here? Is there a way to trigger my action in my top-level component (the one which has the `@provide` decorator)?

**Comment by gaearon** [comment]
```js
store.dispatch(localeActions.fetchLocales());
```

?

**Comment by StevenLangbroek** [comment]
:/ it's available on the store instance? I'm gonna go ahead and bang my head against the wall now, thanks.

**Comment by gaearon** [comment]
No problem. :dancer:
