### ISSUE TITLE
Shared state

### ISSUE THREAD

**Issue by ooflorent** [gaearon/redux#3]
In many cases it is mandatory to share state between components (e.g. `sessionStore`). How can we achieve that using your library since stores are stateless? Could you add an example or an entry to the README?

**Comment by gaearon** [comment]
Can you provide a more specific example? Stores don't *own* the state, but it they still can provide the initial state and return the new versions of it in response to the dispatched actions. From the components' point of view, this doesn't differ from Flux. Components can perform actions and read shared data from the same store. (It's just that internally, it's not Store holding the data.)

**Comment by ooflorent** [comment]
I spoke too quickly. I tried something odd but it still works...
Sorry for the noise.

**Comment by gaearon** [comment]
No problem!
