### ISSUE TITLE
Subscribing to changes from the store doesn't always play nice with hot-reloading

### ISSUE THREAD

**Issue by mvestergaard** [gaearon/redux#301]
When using something like Rx observables to subscribe to changes in the store, it appears that hot-reloading can sometimes cause the subscriptions to be hooked up again, which can cause duplicate events.

**Comment by gaearon** [comment]
Yeah good point. Need to figure this out before shipping 1.0.

**Comment by gaearon** [comment]
Meh, this won't fit into 1.0.
Let's consolidate this with similar issues in #350.

**Comment by gaearon** [comment]
Now we encourage people to use hot module replacement API directly, so that you have full control: https://github.com/rackt/redux/pull/667
