### ISSUE TITLE
Dispatching action from iframe to store defined in parent window always throws

### ISSUE THREAD

**Issue by michalkvasnicak** [gaearon/redux#304]
Dispatching an action from an iframe to store defined in a parent window always throws `Invariant Violation: Actions must be plain objects. Use custom middleware for async actions.`

It fails on the check `Object.getPrototypeOf(obj) === Object.prototype` in `isPlainObject`.

Only way to fix this is to expose actions in the parent window.

**Comment by gaearon** [comment]
Bah! I knew we'd hit something like this :-P
Is there an iframe-friendly plain object check? What is lodash doing?

**Comment by michalkvasnicak** [comment]
I'll take a look. Just a minute.

**Comment by michalkvasnicak** [comment]
Ok lodash is fine. So now we need to figure out what to do so it will behave the same.

**Comment by gaearon** [comment]
Should be fixed by #306!
