### ISSUE TITLE
Can I use Redux with RequireJS?

### ISSUE THREAD

**Issue by arianitu** [gaearon/redux#312]
We have a bunch of existing tools that don't use Redux, but we're interesting in trying it out and I'm not exactly sure if it's compatible.

We're currently using react-router, react-router-shim, jsx-requirejs-plugin and JSXTransformer.

Does Redux work with JSXTransformer and can it be easily included using RequireJS?

**Comment by gaearon** [comment]
If RequireJS lets you use CommonJS modules you can consume Redux as is from NPM.
If not, you can grab the UMD build from NPM in `redux/dist/`.

Does this help?

**Comment by arianitu** [comment]
It seems to load, but I don't know how to access createStore. I thought it would be accessed like so:

```
	var Redux = require("Redux");
	console.log(Redux.createStore);

```

that prints undefined.

I've added this to my RequireJS config

```"Redux": "/node_modules/redux/dist/redux-react.min"```

**Comment by gaearon** [comment]
`createStore` is 1.0 RC API. Are you using 1.0 RC? It is only available if you explicitly `npm install redux@1.0.0-rc`.

**Comment by arianitu** [comment]
Oh I guess I'm not using 1.0.0-RC since I did an npm install. I think that's probably it.

Thanks!

**Comment by gaearon** [comment]
With 1.0 RC, you'll also need to install [react-redux](https://github.com/gaearon/react-redux) separately to get the React stuff.

**Comment by arianitu** [comment]
I just ran into that, thanks!

**Comment by gaearon** [comment]
Similarly, for convenient async dispatches, you'll need [redux-thunk](https://github.com/gaearon/redux-thunk). There's no UMD build there yet, but it's tiny (single function) so you might as well copy that to your project if you need it.

**Comment by arianitu** [comment]
So I looked at the dist folder for react-redux and it has 2 min files:

react-redux.min.js
redux-react.min.js

which one is the correct one? 

Also, I suppose I need to include both redux and redux-react right? So I would do require("ReduxReact") and require("Redux")? Or is Redux included in react-redux?

**Comment by gaearon** [comment]
Woah, it seems like the other one got there by mistake (https://github.com/gaearon/react-redux/issues/9).
It should be `react-redux.min.js`.

>Also, I suppose I need to include both redux and redux-react right? So I would do require("ReduxReact") and require("Redux")? Or is Redux included in react-redux?

You would get `createStore` from `require('redux')`, but React components (`Provider`, `Connector`) from `require('react-redux')`.

**Comment by festaans** [comment]
`var createStore = require('redux').createStore`

From: http://redux.js.org/docs/api/
