### ISSUE TITLE
Cost of immutability

### ISSUE THREAD

**Issue by scisci** [gaearon/redux#328]
im excited about this project but worried that this technique of creating a new state object on every change to the store would tax the gc and performance in a large application. Would be good to see some tests or explanations about why I shouldn't be worried about this

**Comment by gaearon** [comment]
Well, [Om](https://github.com/omcljs/om) apps work exactly like this and don't seem to have these kinds of problems. When you want to squeeze additional bits of performance, you can use [Immutable](https://facebook.github.io/immutable-js/) or [Mori](http://swannodette.github.io/mori/) which, unless I am mistaken, better utilize memory by implementing persistent data structures using structural sharing.

Finally, nothing *per se* prevents you from mutating your Redux state tree. It is actively discouraged, and you will lose a lot of debugging benefits if you mutate your data, but for performance critical pieces you can write impure reducers that mutate the state in place. (Only do that if you're *sure* that's where the lag comes from—not likely to be an issue in real apps.)

**Comment by gaearon** [comment]
Don't forget that even with traditional Flux you're still likely to allocate objects in your store getters or in your components' `setState` method calls. It's not like one or two objects allocated with Redux will change much.

**Comment by scisci** [comment]
Thanks for your response. It could very well be a more generic react/flux question (I'm new to both). Thanks for addressing it anyway. I'm only planning on building a traditional web app for now, but who knows, might want to create a web version of After Effects one day...

**Comment by inkless** [comment]
This is exactly the same concern as mine. Thanks for the explanation.

**Comment by deathmood** [comment]
@gaearon just looked into [redux.js.org - 3 principles](http://redux.js.org/docs/introduction/ThreePrinciples.html) and there:

```
State is read-only
The only way to mutate the state is to emit an action, an object describing what happened.
```

like some kind of misconception --- because as far as I understand _**mutating**_ state is very discouraged
