### ISSUE TITLE
Doc improvements / tutorial for newbs?

### ISSUE THREAD

**Issue by anyong** [gaearon/redux#329]
Hello there,

Been reading the API docs and two examples provided, there's really not much to go on for somebody completely new to redux. I know plenty of people following this repo think it's simple and self-explanatory, but as a newcomer I can tell you it definitely is not. Would love to have a basic tutorial that walked through setting up a redux / react-redux environment that can help me understand not just what the functions do (as in the API docs) but how to use them in actual code and what purpose they serve / when to use which one.

Also looked at a few starters but those provide even less explanation, just a bunch of code that I am as yet not able to understand.

(I'm sure somebody will paste another repo here with some examples - I've probably already seen them, unless there's actually a tutorial that I've missed. I'm talking about an actual tutorial/explanation though, not just more code.)

Thanks!

**Comment by gyzerok** [comment]
@anyong If you did not understand all from the readme I guess you are not understanding Flux. So the first option for you is to read about Flux. There are a lot of tutorials about it so you can find which best suits to you. After it check [this article](https://medium.com/@dan_abramov/the-evolution-of-flux-frameworks-6c16ad26bb31).

**Comment by anyong** [comment]
@gyzerok I'm completely fine with at least two implementations of flux: Reflux and Fluxible. Neither of those uses the dispatcher in exactly the same way as Facebook's original flux but same idea. I read through the article you linked, which was basically covering some of the things Dan mentioned in his talk at React Europe.

I understand the concept of using a reduce function, and of having a single state object. I think what I'm not understanding is the sudden introduction of middleware and how it is analogous to middleware that I'm familiar with (i.e. in a web server), and how to compose reducers to form a single state object similar to how react components are composed to form a single react element.

I've tried following some of the example code and writing my own modules from scratch to see how it works. Every time so far I just end up with some error or another, most recently:

`Uncaught Error: Invariant Violation: Expected the reducer to be a function.`

**Comment by gyzerok** [comment]
@anyong How do your reducers look like? If you can provide link to your code I may try to help you.

I guess the best for you is to wait until 1.0 release with up to date documentation about all those things you mentioned.

**Comment by tundrax** [comment]
@anyong If you are using v1.0.0-rc then https://github.com/gaearon/redux/blob/improve-docs/docs/getting-started.md is good place to follow API updates.

**Comment by anyong** [comment]
@tundrax thanks, seems I missed this folder which answers a lot of my questions.

**Comment by tundrax** [comment]
:+1:

**Comment by yang-wei** [comment]
Hi if you want to see how redux can be used on other libraries than react, I made an example of vuejs plus redux. 

https://github.com/yang-wei/vue-flux

**Comment by xgrommx** [comment]
This is the full list of Redux examples https://github.com/xgrommx/awesome-redux

**Comment by gaearon** [comment]
We're working on docs! We don't think it's self-explanatory at all ;-)

**Comment by anyong** [comment]
I would be happy to contribute to docs, just as soon as I can wrap my head around what's going on here! My latest attempt is getting there, but still no dice... https://gist.github.com/anyong/46fa22162e06a0a892af

**Comment by gaearon** [comment]
@anyong Can you explain the problem? It's hard to guess :-)

**Comment by anyong** [comment]
I wish I could, then I might know what was wrong! All I can say at the
moment is that my store is connected because Master.jsx line 30 displays
initially with the initial state, but it never updates after I log in with
the fake username and password john/password.

I see the action fire and the store gets the correct payload, but nothing
happens on the component.

**Comment by gaearon** [comment]
@anyong 

Your `auth` reducer looks suspicious to me. `return assign(initialState, ...)` will mutate the initial state and completely disregard the up-to-date `state` passed to the method. Moreover `return initialState` in the `default` case means you're completely resetting the state every time an unknown action fires.

Shouldn't it be

```js
export default function auth(state = initialState, action = {}) {
    switch (action.type) {
        case LOGIN_REQUEST:
            return assign({}, state, {loggingIn: true});
        case LOGIN_SUCCESS:
            return assign({}, state, action.payload, {loggedIn: true});
        case LOGIN_FAILURE:
            return assign({}, state, {error: true});
        default:
            return state;
    }
}
```

instead?

**Comment by anyong** [comment]
@gaearon Yes, that's it. Yargh, that's smart. So actually if we mess up the store and modify state instead of writing a pure function, it simply doesn't work. Thanks :)

**Comment by gaearon** [comment]
Closing, as there doesn't appear to be a specific issue.
