### ISSUE TITLE
Release date for 1.0?

### ISSUE THREAD

**Issue by gyzerok** [gaearon/redux#330]
More than a month have passed since alpha release. It seems like you trying to do all possible things in 1.0. Mb its time to stop and release? :) 1.0 shouldnt be your final version. You can release 1.1 and even 2.0 later.

With high impatience and love to Redux idea, gyzerok.

**Comment by theaqua** [comment]
https://github.com/gaearon/redux/milestones/1.0
https://github.com/gaearon/redux/issues/164

What is a question?

**Comment by gyzerok** [comment]
@theaqua thanks for the link

**Comment by gaearon** [comment]
The only blocker for 1.0 is the docs.
We can't possibly release 1.0 without the docs for it, can we?

That's what I'm working on (and I'd appreciate some help!)
#289

**Comment by gaearon** [comment]
1.0 is out.
