### ISSUE TITLE
React + RXjs or React + Redux or something else ?

### ISSUE THREAD

**Issue by vieks** [gaearon/redux#333]
Hi,
I am at the beginning of a large project. And I must chose a suitable techno/pattern which fit well with component UI design.

But I am a bit confusing and lost about it.

There is a plenty implementation of Flux and it seems that Redux is the best choice right now. But for how long ?

The Flux ecosystem is moving very fast to another and its scares me. Indeed, I don't want to start a 
new important project and 6 mouths later refactoring all my UI/frontend code due to a forsaken repo with no more update/follow.

So what do you think of ?

And what about functional reactive programming alternative with RXjs alike lib instead of Flux at pattern ?
Can it be more productive and relevant for the futur ?

If someone have a background and experiment on it, thanks to share your mind :)

PS: Sorry for my poor english :(

**Comment by gaearon** [comment]
We strive to have the least amount of API possible so you won't be “locked into” Redux. If you write your data mutations are reducer functions, you can port them to any other Flux library later, or even to Rx.

These docs (work in progress, soon will be merged into master) should help:

https://github.com/gaearon/redux/blob/rewrite-docs/docs/Basics/Migrating%20to%20Redux.md
https://github.com/gaearon/redux/blob/rewrite-docs/docs/Basics/Relation%20to%20Other%20Libraries.md

**Comment by vieks** [comment]
Thanks @gaearon. I finally use your lib it's an amazing piece of software.
Keep going your great job !
