### ISSUE TITLE
Hot reloading resources outside of React (server rendering)

### ISSUE THREAD

**Issue by mridgway** [gaearon/redux#340]
The examples that show hot reloading of reducers depend on the redux instance being instantiated within a React component. This works for client-only apps, but when you use server-rendering, you need to bootstrap the application and its state prior to calling `React.render`. Many of the isomorphic examples I've looked at do not work with hot reloading because the reducers are required from a client bootstrap file instead of the top-level app component. It seems like there would have to be some `module.hot` magic for hot reloading within server-rendered apps.

**Comment by gaearon** [comment]
Might be related: https://github.com/gaearon/redux/issues/301

**Comment by gaearon** [comment]
I think we want to understand how to do this before 1.0 is shipped.

**Comment by wmertens** [comment]
@mridgway cool I never considered server side hot reloading! Do you have a code example?

**Comment by mridgway** [comment]
@wmertens This isn't server-side hot reloading. The client bootstrapping code has to be moved outside of React when rendering on top of existing markup vs. rendering fully on the client.

**Comment by gaearon** [comment]
@mridgway 

Does something like

```js
import * as reducers from './reducers';

// ...

let store = createStore(combineReducers(reducers));

// ...

React.render(<Stuff />, ...);

if (module.hot) {
  module.hot.accept('./reducers', function () {
    store.replaceReducer(combineReducers(reducers));
  });
}
```

work?

**Comment by gaearon** [comment]
Let's continue the discussion in #350.

**Comment by gaearon** [comment]
Now we encourage people to use hot module replacement API directly, so that you have full control: https://github.com/rackt/redux/pull/667
