### ISSUE TITLE
How to separate stores and filter actions 

### ISSUE THREAD

**Issue by eguneys** [gaearon/redux#341]
I have a play store with initial state `cards`.
I can withdraw cards.

`PlayStore.js`

```
let initialState = {
  cards: []
}

export default createReducer(initialState, {
  [types.WITHDRAW_CARD](state) {
    state = state.update('cards', cards => cards.push(10));
    return state;
  }
});
```

I have another store for keeping the rules for the game.
It holds the state for if it has withdrawn a card or not.

`PlayRulesStore.js`

```
let initialState = {
  hasWithdrawn: false
}

export default createReducer(initialState, {
  [types.WITHDRAW_CARD](state) {
    state.set('hasWithdrawn', true);
  }
});
```

Now I need to set a rule if it has already withdrawn a card, I can't withdraw a card anymore.

What is the best way to state this logic. This is just a simple example but I have a lot of rules so I want to keep rules store seperate from the play store, so it would be easy to test.

One possible solution would be to define this logic in action creators:

`GameActions.js`

```
export function tryWithdrawCard() {
  return (dispatch, getState) {
    let ruleState = getState()['PlayRules'];
    if (!ruleState.get('hasWithdrawn')) {
      dispatch(withdrawCard());
    }
  }
}

export function withdrawCard() {
  return {
    type: WITHDRAW_CARD
  }
}
```

Something like this, I suspect there is a better solution to this please help.

Another problem is that a rule depends on the play state. For example, I can withdraw only if I have less than 5 cards. So the rule store depends on the play store somehow.

**Comment by cesarandreu** [comment]
Rx seems like it might be a nice fit for modeling something like this. It might be worth checking out.

I don't really understand what PlayRulesStore is being used for.

**Comment by gaearon** [comment]
What you suggested with action creators is exactly how I'd do it.
