### ISSUE TITLE
no trigger re-render with ajax

### ISSUE THREAD

**Issue by cswleocsw** [gaearon/redux#342]
Hello:
I try to use redux (1.0.0-rc ) to build a new application, but I encountered some problems that components is not re-render when i use actions to trigger actions.

I think it should be I do not underscore what redux's magic skill.
If you have time, can you help me to examine the test code.

[issue@render](https://github.com/cswleocsw/react-test/tree/issue%40render)

thanks.

**Comment by gaearon** [comment]
The reducer code mutates the given state:

```js
        case REQUEST_SUCCESS:
            assign(state, action.payload);
            return state;
```

This won't work. You need to create a copy of the state every time:

```js

        case REQUEST_SUCCESS:
            assign({}, state, action.payload);
            return state;
```

or, using ES7 spread syntax proposal,

```js

        case REQUEST_SUCCESS:
            return { ...state, ...action.payload };
            return state;
```

Does this solve your problem?

**Comment by cswleocsw** [comment]
I think I know what the point of my question, thanks.
