### ISSUE TITLE
calling actions from within an action?

### ISSUE THREAD

**Issue by eelkeh** [gaearon/redux#344]
As discussed in #316 a way to deal with nested data is to normalize them into their own (hashmap) stores, as in `{id => { ... values}}`. Let's say we have two stores slices `{ movies: { castId, title, ... }, cast: {id, name, age}` and we want to add a new cast member to a movie. 
We would then have to add a member to the `cast` store and a reference (`castId`) to the movie. I could imagine having an action `addCastMemberToMovie`, but we need to add the castmember to the `cast` slice first. So should we call a `addCastMember` action from within `addCastMemberToMovie`? Is this good practice, as it doesn't keep actions "simple", but chains them in a way? Maybe there's another way? Any input would be greatly appreciated!

**Comment by gaearon** [comment]
Is it up the client to generate an ID? Usually server does that. Can you clarify your requirements please?

**Comment by eelkeh** [comment]
In this case, the client generates the ID yes. What I'm looking for is a way to first add the new object to `cast` store, and then add the ref to the `movie`, should I call an action from within an action? I'm not sure where this logic should belong.

**Comment by gaearon** [comment]
If the client generates an ID, where does that happen? Since reducers should be deterministic, it sounds like you want to generate an ID in the action creator. With [redux-thunk](https://github.com/gaearon/redux-thunk) (or without it if you're using 0.12) your code could look like:

```js
function registerCastWithId(id, name) {
  return { type: REGISTER_CAST, id, name };
}

function generateNextId() {
 // ...
}

export function registerCast(name) {
  return dispatch => {
    let id = generateNextId();
    dispatch(registerCastWithId(id, name));
    return id;
  }
}
```

Then your component can do this:

```js
handleClick() {
  let { name, movieId } = // ...
  let castId = this.props.dispatch(registerCast(name));
  this.props.dispatch(addToCast(castId, movieId));
}
```

So yes, indeed, these should be two separate actions called by one component. If one of them becomes async, the distinction is even more clear. Creating a new entity and binding it to another entity are two separate actions.

**Comment by eelkeh** [comment]
Thanks a lot for the quick reply and great explanation!

**Comment by gaearon** [comment]
Another argument in favor of separating them is you want to `addToCast` sometimes for an *existing* entity. It's not like they're always being created.

**Comment by ForbesLindesay** [comment]
You could alternatively have them be a single action but have the cast store ignore the action if that cast member already exists.

**Comment by gaearon** [comment]
Yeah. It's convenient to do in AC if there's an async API call you'd like not to do if there's a cached value.

**Comment by bcgarcia** [comment]
i have one file called userActions that contains action functions for users and other file called notificationAction that contains action functions to show notifications. I want to dispatch notification action when an user register ok or if an user register fails .

I tried to import notificationActions into userActions and dispatch the function declared in notificationActions but i get an error :  ReferenceError: addNotification is not defined.

its ok doing this or i have to do something wrong?
