### ISSUE TITLE
using replaceReducer in module

### ISSUE THREAD

**Issue by rt2zz** [gaearon/redux#348]
I am contemplating having https://github.com/rt2zz/redux-persist use replaceReducer to implement a "auto rehydration" feature. Basically it would apply a higher order reducer behind the scenes to do some custom handling on rehydration actions. 

The question: is it safe / idiomatic to use replaceReducer outside of development tools / hot reloading?

**Comment by gaearon** [comment]
Better not to rely on them. They're a temporary escape hatch and I foresee we'll have a better solution soon after 1.0 ships.

**Comment by gaearon** [comment]
Let's continue the discussion in #350.
