### ISSUE TITLE
`storeKeys[store[key]]` isn't working if all stores wrapped by `createStore`

### ISSUE THREAD

**Issue by vslinko** [gaearon/redux#35]
I think `Function.prototype.toString()` smells isn't good

**Comment by vslinko** [comment]
https://github.com/gaearon/redux/blob/09f8aaee981ef19bb7342b7728f750e131249cb5/src/createDispatcher.js#L79

**Comment by gaearon** [comment]
Oh man. I totally meant to use `get` and `set` of ES6 Map instead.

**Comment by gaearon** [comment]
Should be good in 0.6.1, can you verify?

**Comment by vslinko** [comment]
Yep, works well
