### ISSUE TITLE
Update official examples

### ISSUE THREAD

**Issue by xgrommx** [gaearon/redux#353]
Hello @gaearon. Could you please update official examples to last version of redux and react-redux?

**Comment by knowbody** [comment]
here they are @xgrommx https://github.com/gaearon/redux/tree/breaking-changes-1.0/examples

**Comment by xgrommx** [comment]
@knowbody This is final api?

**Comment by knowbody** [comment]
@xgrommx this is work in progress on Redux 1.0

**Comment by gaearon** [comment]
Yes, it's what we'll release as 1.0 once the docs are ready.

**Comment by gaearon** [comment]
API reference for 1.0 is complete too: https://github.com/gaearon/redux/tree/rewrite-docs-again/docs/API%20Reference

More docs coming.

**Comment by xgrommx** [comment]
@gaearon This doc include api for react-redux?

**Comment by gaearon** [comment]
@xgrommx 

No, I'll put the API reference for `react-redux` in its own repo and will link to it.
A “Getting Started” guide in Redux repo will include `react-redux` instructions, but not its full API.

**Comment by gaearon** [comment]
I'm closing because examples in the 1.0 branch are up to date.
