### ISSUE TITLE
getState() with selector

### ISSUE THREAD

**Issue by svagi** [gaearon/redux#367]
I'm not sure, if somebody already ask about this, but what about extending [getState()](https://github.com/gaearon/redux/blob/v1.0.0-rc/src/Store.js#L44) with a selector? 

Maybe something like:
```javascript
getState(select = state => state) {
    return select(this.state);
}
```
Then you can use it with the selector:

```javascript
store.getState(state => state.user);
```
Or with the wrapper selector:

```javascript
store.getState(state => ({ user: state.user }));
```

Or staying imperative as usual

```javascript
const { user } = store.getState();
```

**Comment by gaearon** [comment]
What does this win over simple function application?
I need to stress we want to keep core API as simple as possible: #303.

**Comment by gaearon** [comment]
I'll close for the same reasons as #303: we need this API to stay as "raw" as possible so it's easy to extend for store enhancers. Higher-level APIs may be built on top of `getState` and `subscribe`.
