### ISSUE TITLE
Suggestion:  Possible changes 

### ISSUE THREAD

**Issue by mikekidder** [gaearon/redux#38]
1) In **Counter.js**,  fat arrow functions; lexical bind to 'this' not needed in this case.  Still demonstrated in Todo example.

```javascript
<button onClick={() => increment()}>+</button>
``` 
to
```javascript
<button onClick={increment}>+</button> 
```

2) On the Counter example, change the imports for ActionTypes:

```javascript
import {
  INCREMENT_COUNTER,
  DECREMENT_COUNTER
} from '../constants/ActionTypes';
```
to
```javascript
import * as types from  '../constants/ActionTypes';
```
and then use accordingly in case statements, etc..
```javascript
 types.INCREMENT_COUNTER
```

**Comment by gaearon** [comment]
Yeah, not really needed. I wanted to avoid leaking `e` argument to the action creators though. Maybe I shouldn't bother in the README :-)

If you PR this I'll merge it.

**Comment by mikekidder** [comment]
PR #40 for the first one is ready. Did you want the second one, or leave it as is?

**Comment by gaearon** [comment]
@mikekidder Please make them look the same? (with destructuring).
