### ISSUE TITLE
Question: where this the place for keeping "isLoading" state?

### ISSUE THREAD

**Issue by tadjik1** [gaearon/redux#391]
Hello. Thanks for a perfect work and very useful tool!
We are trying to use it in our project and meet a next difficult situation:

we have a movies collection in our project. movies could be recommendation, new releases, free, etc. How should we construct our store for keep all of this types and movies and how we detect that free movies are loading but new releases already loaded? All of this collections are paginated.

for example movies reducer:

```javascript
const initialState = {
  allMovies: {}, // id => movie
  free: [], // id
  releases: [], // id
  ...,
  search: new Map() // {search query} => [id1, id2, ...]
};

export default function movies(state = initialState, action) {
  const movies = selectn('payload.entities.movies', action);
  const ids = selectn('payload.result.movies', action);

  switch (action.type) {
  case RECEIVED_NEW_RELEASES:
    // add movies and return new state

  case RECEIVED_FREE_MOVIES:
    // add movies and return new state
  default:
   // return state
  }
}
```

So, how can I detect that my request for free movies is in process or finished? Where this state should be placed?

**Comment by gaearon** [comment]
It's sensible to store `isFetching` together with other pagination information. Your data structure most likely will look like this:

```js
const initialState = {
  allMovies: {}, // id => movie
  free: {
    ids: [],
    nextPageUrl: string, // empty on last page, parsed from server response
    isFetching: bool
  },
  releases: {
    ids: [],
    nextPageUrl: string, // empty on last page, parsed from server response
    isFetching: bool
  },
  ...,
  search: new Map() // {search query} => [id1, id2, ...]
};
```

It's also sensible to make something like `createPaginationReducer(actionTypes)` so you don't need to write this logic more than once.

**Comment by tadjik1** [comment]
@gaearon Thanks!
