### ISSUE TITLE
npm bundle has two different browser builds

### ISSUE THREAD

**Issue by constb** [gaearon/redux#396]
in ``/dist`` there are ``react-redux.js`` and ``redux-react.js``. both minified. what's even more confusing is that they have different size. I think one should be removed.

**Comment by constb** [comment]
damn it, I posted it to the wrong project. it's about ``react-redux`` of course. should I reopen it there?

**Comment by dariocravero** [comment]
@constb see this https://github.com/gaearon/react-redux/pull/11 :)

**Comment by gaearon** [comment]
We'll fix that after getting Redux 1.0 out. Sorry :-P
