### ISSUE TITLE
Action types as symbols

### ISSUE THREAD

**Issue by ooflorent** [gaearon/redux#4]
Allowing this would be awesome.
Why did you enforce `type` as `string`? ([createDispatcher.js#L67](https://github.com/gaearon/redux/blob/789b548f065b16b1ca3c1057bf97e0a23610e087/src/createDispatcher.js#L67))

```js
export const INCREMENT_COUNTER = Symbol()
export const DECREMENT_COUNTER = Symbol()
```

**Comment by gaearon** [comment]
I thought of that, but this kind of screws the replay thing. (AFAIK you can't serialize and then deserialize symbols.) I want to pass them around for devtools, localStorage persistence, etc.

**Comment by ooflorent** [comment]
You're right you cannot deserialize a `Symbol`. I've missed that point.

**Comment by gaearon** [comment]
I say let's keep them strings for now and revisit if there are ways to get around (de)serialization problem.

**Comment by tbranyen** [comment]
I might be confused here, but what do you mean by "cannot deserialize a Symbol"?

``` javascript
const INCREMENT_COUNTER = Symbol('INCREMENT_COUNTER');

console.log(String(INCREMENT_COUNTER)); // Symbol(INCREMENT_COUNTER)
```

Wouldn't this be perfectly ideal for Redux? The ability to have identically named action types that are namespaced. I'm absolutely hating the fear that action types are overlapping since everything is global.

**Comment by tbranyen** [comment]
I just tried using a Symbol and thankfully it works excellent with Redux! The only error that came up was with redux-logger, so I'll narrow down the error and submit a patch (if one isn't already there).

**Comment by gaearon** [comment]
You can't take an array of actions that use symbols, serialise them to JSON, save to localStorage, and later deserialise and replay them in a different browser session.

**Comment by tbranyen** [comment]
@gaearon I see what you mean, that is very true. For my use case it won't be a problem, and I've submitted a patch request for redux-logger here: https://github.com/fcomb/redux-logger/pull/106

(Sorry for spamming this particular issue, but I think it's useful for others looking to use Symbols).
