### ISSUE TITLE
Reducer handling action meta data

### ISSUE THREAD

**Issue by malte-wessel** [gaearon/redux#408]
Hey folks, I was wondering if the following is valid:

* I've got a middleware that handles promises; If the payload is a promise, the middleware handles the promise and forwards the action with some meta information:

```javascript
{
  type: 'TASKS_FETCH',
  meta: {
    promise: true,
    status: 'PENDING'
  }
}
```
When the promise is resolved or rejected a corresponding action is triggered which looks like this:

```javascript
{
  type: 'TASKS_FETCH_SUCCESS',
  meta: {
    promise: true,
    status: 'SUCCESS'
  }
}
```

Now, I want a `loading` reducer to react to those actions and count how many promises are pending:

```javascript
const initialState = { count: 0 };

export default function loading(state = initialState, action) {
	if (action.meta && action.meta.promise) {
		switch (action.meta.status) {
			case 'PENDING':
				return {
					count: state.count + 1
				};
			case 'SUCCESS':
			case 'ERROR':
				return {
					count: state.count - 1
				};
			default:
				return state;
		}
	}

	return state;
}
```
What do you think, is handling meta data inside a reducer valid, do you see any problems?

**Comment by gaearon** [comment]
This looks totally sensible to me.
