### ISSUE TITLE
Showing notifications from reducers

### ISSUE THREAD

**Issue by bkniffler** [gaearon/redux#421]
Hey, 
I'm still trying to wrap my head around redux.

Now, I've created a store that would trigger notifications:
```javascript
import {
   CRUD_SAVE_SUCCESS,
} from '../actions/action-types';

const initialState = {
};

export default function notification(state = initialState, action = {}) {
   console.log("Trigger", action.type);
   switch (action.type) {
      case CRUD_SAVE_SUCCESS:
         window.addNotification({
            message: "Saved.",
            level: "success",
            title: "Status"
         });
         return state;
      default:
         return state;
   }
}

```

Problem is, a new notification is created every time the state changes. The console log showed to me, that every time the state changes, all previous actions are re-triggered. This results in a new notification for each state-change for each time `CRUD_SAVE_SUCCESS` is called, so 2 calls result in 2 notifications the next time `SOME_ACTION` is triggered. 

Is that the normal behaviour? Or might I have a bug somewhere in my code? Any idea how I could solve that problem?

Thanks!

**Comment by gaearon** [comment]
Your reducers (using 1.0 terminology) should not contain any side effects. They should be pure functions, just like `render()` function in React.

You want to do side effects in action creators instead. Can you show your action creator for `CRUD_SAVE_SUCCESS`?

**Comment by bkniffler** [comment]
Okay, got it, thanks for the hint. Here is the action creator:

```javascript
export function save(model, instance) {
   return {
      types: [CRUD_SAVE, CRUD_SAVE_SUCCESS, CRUD_SAVE_FAIL],
      promise: (client) => client.put("/" + model + "/" + instance.id, instance).then((result)=>{
         window.addNotification({
            message: "Saved.",
            level: "success",
            title: "Status"
         });

         return {
            data: result,
            model: model
         }
      }, (error)=>{... gotta show error})
   };
}
```

Using @erikras middleware
```javascript
export default function clientMiddleware(client) {
   return ({/* dispatch, getState */}) => {
      return (next) => (action) => {
         const { promise, types, ...rest } = action;
         if (!promise) {
            return next(action);
         }

         const [REQUEST, SUCCESS, FAILURE] = types;
         next({...rest, type: REQUEST});
         return promise(client).then(
            (result) => next({...rest, result, type: SUCCESS}),
            (error) => next({...rest, error, type: FAILURE})
         );
      };
   };
}
```

**Comment by gaearon** [comment]
This makes sense!
