### ISSUE TITLE
How to test smart component?

### ISSUE THREAD

**Issue by alexbyk** [gaearon/redux#447]
Could you pls provide an example how should I test smart components like "containers/App.js" from http://gaearon.github.io/redux/docs/basics/ExampleTodoList.html

Thanks

**Comment by gaearon** [comment]
Which behaviors do you want to test? It's not really a “unit” test if you attempt to test the whole app.

**Comment by alexbyk** [comment]
Thanks for the answer, @gaearon 
I'm not sure. There is a lot of code at `containers/App.js`... And it would be good to test it (even not really "unit" tests would be good enough). You've wrote an excellent [Writing tests](http://gaearon.github.io/redux/docs/recipes/WritingTests.html) article, it covers all parts from TodoApp except this "smart component".

For example, how to test that`<App/>` contains/renders `<Footer/>` with correct `filter={visibilityFilter}`? 

How to use:`TestUtils.renderIntoDocument`  with the smart `App.js` and then find `Footer` with `scryRenderedComponentsWithType`?

**Comment by alexbyk** [comment]
So I ended up with splitting the "smart component"  term (`containers/App.js') into "React Container" + "Redux Page".  This makes possible to test containers like a normal React Classes...  Also the whole app (not only the components) becomes independent from 'Redux'
