### ISSUE TITLE
remove actions from props

### ISSUE THREAD

**Issue by threepointone** [gaearon/redux#45]
Was wondering how you handle clashing action and store names in containers. But it also strikes me that since actions are just functions *without* a current state, they don't have to be passed down from the top. Instead, as long as the dispatch function is available as a prop, you'll still be able to do full dispatches. to explain, instead of - 
```js 
@inject({
  actions: CounterActions,
  stores: { counter: counterStore }
})
export default class Counter {
  render() {
    const { increment, decrement, counter } = this.props;
    return (
      <p>
        <button onClick={increment}>+</button>
      </p>
    );
  }
```
you could do 

```js 
@inject({
  stores: { counter: counterStore }
})
export default class Counter {
  static propTypes = {
    dispatch: PropTypes.func.isRequired
  };

  render() {
    const { counter, dispatch } = this.props;
    return (
      <p>
        Clicked: {counter} times
        {' '}
        <button onClick={() => dispatch(increment())}>+</button>
        {' '}
        <button onClick={() => dispatch(decrement())}>-</button>
      </p>
    );
  }
```
alternately

```js 
        <button onClick={() => dispatch(increment)}>+</button>
```

but I'm not clear on the benefits (scheduling?) 

This would clear up the name clash problem, and make it more 'primitive', if that make sense.

**Comment by threepointone** [comment]
also, you could then read state from stores when calling `dispatch`, preventing the need for `read`/`storeKeys`

**Comment by threepointone** [comment]
thinking more, anyone could implement any action creator system on top of this. promises, observables, etc. 

[it's starting to look like cycle, but more accessible]

**Comment by gaearon** [comment]
cc @acdlite who was also [rethinking Redux](https://gist.github.com/acdlite/9f1b5883d132ad242323). Indeed, I want to move this action creator <-> dispatch thing out of the core.

**Comment by gaearon** [comment]
This is done now in #46, let's discuss there.

**Comment by gaearon** [comment]
https://github.com/gaearon/redux/pull/46#issuecomment-109595200

**Comment by threepointone** [comment]
Wow lots going on there. I want to hack on a project tonight with this, will come back with thoughts. Cheers.

**Comment by gaearon** [comment]
Out in 0.8.0
