### ISSUE TITLE
Handling big states in reductor

### ISSUE THREAD

**Issue by razjel** [gaearon/redux#454]
I'm writing large TypeScript application and my state got quite complex and nested. That's how my example state for particular reductor looks (I know that this can be simplified, but for the sake of my case let's say I need to have such structure, because there will be more parameters):
```javascript
class AllPhotoData {
  public photoDatas:OrderedMap<string,PhotoData>; //this class works similiar to ES6 Map, but it also remebers order in which items were added
}
class PhotoData {
  hash:string;
  mimetype:string;
  printParams:PrintParams;
}
class PrintParams {
  size:string;
  paper:string;
}
```

When I want to change property `size` in reductor, do I need to create new instance of each object above last param, which would look sth like this:
```javascript
case "UPDATE_SIZE":
  //clone() - returns shallow copy
  state.photoDatas = state.photoDatas.clone();
  state.photoDatas.replace(state.photoDatas.get(action.hash).clone());
  state.photoDatas.get(action.hash).printParams = state.photoDatas.get(action.hash).printParams.clone();
  state.photoDatas.get(action.hash).printParams.size = action.newSize;
  return state;
```
or is it enough to update only parent object which contains changed data?
```javascript
case "UPDATE_SIZE":
  state.photoDatas.get(action.hash).printParams = state.photoDatas.get(action.hash).printParams.clone();
  state.photoDatas.get(action.hash).printParams.size = action.newSize;
  return state;
```

**Comment by gaearon** [comment]
>do I need to create new instance of each object above last param

Yes.

>or is it enough to update only parent object which contains changed data?

No.

If you change something deeply, you *need to* change the reference to change at every level upwards. This is why using custom classes for Redux state isn't a very good idea.

If you often need to change state deeply and you are concerned about performance, use [Immutable.js](https://facebook.github.io/immutable-js/) which utilizes structural sharing for minimal memory overhead on deep changes. It also has nice APIs like [`mergeDeep()`](https://facebook.github.io/immutable-js/docs/#/Map/mergeDeep) to help with this.

**Comment by cesarandreu** [comment]
@razjel to add a bit to what @gaearon said, one feature of immutable.js that you should be aware of is [withMutations](http://facebook.github.io/immutable-js/docs/#/Map/withMutations). It lets you perform multiple changes (which you typically want to do in your reducers) without having to create an intermediate object for each, so the memory cost is reduced even further.
