### ISSUE TITLE
Useless code in applyMiddleware.js?

### ISSUE THREAD

**Issue by jacobbubu** [gaearon/redux#457]
https://github.com/gaearon/redux/blob/rewrite-docs-again/src/utils/applyMiddleware.js#L28-L31

``` js
export default function applyMiddleware(...middlewares) {
      ...
      let middlewareAPI = {
        getState: store.getState,
        dispatch: (action) => dispatch(action)
      };
      ....
```

What does `middlewareAPI` use for?

**Comment by knowbody** [comment]
yeah, it looks like it. I think this stayed there from [this commit](https://github.com/gaearon/redux/blob/ac8a1841fbdae5f6c94363583cdfaaf792ffba90/src/utils/applyMiddleware.js)

**Comment by gaearon** [comment]
That code was actually broken and committed by mistake. It's fixed now.
