### ISSUE TITLE
Stores organisation

### ISSUE THREAD

**Issue by dmongeau** [gaearon/redux#470]
I was just wondering how people organize their stores. My first tough was to organize by "type" of components so for example, having a `ListItemsStore`, where every lists components will store their items by their list name. The list component is then responsible to trigger actions related to it's item type and then play with ListItemsStore to update it's items.

So for example, if I have a `UsersListComponent`, he can dispatch a `UserActions.createUser(newUser)` wich will issue a post to the server returning the new user. The async `UserActions.createUser` action then dispatch a `ListActions.addItem('UsersListComponent', newUser)` action to update the list store which will then update the `UsersListComponent` component. This works well for some times.

The main problem I'm facing right now, is if another Component is using the users list. Having the stores related to the components type is not really the best choice in that case because other component won't get updated. Either I dispatch all the actions that needs to be done to keep the other stores in sync in the `UserActions.createUser`, or I use a more general store related to entities instead of components, in this case a `UsersStore`. But then, how does my component knows that they want only a subset of the data contained in the `UsersStore`? I can't find a nice solution.

And in the coming of Relay and "Components that declare the data they needs" I can figure out how the components will be using the same "user id:14 object" to ensure that if it is updated by component dispatching an action, every components that uses it will get updated.

Really needs help on that.

Thanks in advance

**Comment by gaearon** [comment]
Keep your state normalized like a database. New "real-world" example in breaking-changes-1.0 branch should give some idea.

**Comment by dmongeau** [comment]
Ok but then I need some query engine on the client side to pull the data my component needs?

Also I forgot to mention that i'm working on applications where there is multiple React component on the page not sharing the same root component. They are sharing the same redux instance and stores though. But it's possible that a component needs a UsersStore and another too, but not with the same items, but probably some users are common to both component. This is where I get lost. It seems (in my head), either I split all the stores by "component" with the nightmare of propagating the changes everywhere, or everyone use the same store with the components querying only what it needs (which can get very complex).

Also I love graphql a lot because it gives you the exact object and structure you want, but it seems to have the same problem, how can I be sure that the user id:14 gets updated in every components that has a query that can possibly contains this particular user.. Should I refetch every component just to be sure?

Will look at the examples. Thanks a lot!

**Comment by dmongeau** [comment]
I guess what I was dreaming for is https://github.com/gaearon/normalizr :) Thanks a lot
