### ISSUE TITLE
Trying to follow basic example, getting "`this.dispatchFn` is not a function"

### ISSUE THREAD

**Issue by gryzzly** [gaearon/redux#472]
Using following code, I'm getting 
```
Uncaught TypeError: this.dispatchFn is not a function 
dispatch @ lib/Redux.js:49(anonymous function) @ lib/index.js:34
```

```js
var createRedux = require('redux').createRedux;
var reducer = function (state, action) {
  return state;
};
var redux = createRedux(reducer);
redux.dispatch({
  type: 'FOO',
  payload: {}
});
```

Am I missing something obvious? 

Thanks!

You can view the console in the requirebin to see the same error:
http://requirebin.com/?gist=b260a9d89eaad8bbf84c

**Comment by gaearon** [comment]
You're running the example for 1.0RC, on 0.12.
Use `redux@1.0.0-rc` and it will work as described.
We'll soon publish `1.0.0` so this problem will go away completely.

**Comment by gryzzly** [comment]
Gotcha, thanks for the quick reply!

**Comment by vincentfretin** [comment]
@gaearon I had a hard time to install 1.0.0-rc myself actually. What I did was to add "redux": "1.0.0-rc" in packages.json and then run npm install. I didn't know I could do "npm install --save redux@1.0.0-rc". I'm used to redux=1.0.0-rc syntax in other packages manager (apt-get or pip), I didn't try @. The README doesn't tell you how to install the release candidate.

**Comment by gaearon** [comment]
@vincentfretin Thanks for the PR.
