### ISSUE TITLE
Should we pass the initial value of the reducer to mapValues?

### ISSUE THREAD

**Issue by happypoulp** [gaearon/redux#478]
Hi,

I was trying to test the assumption that "mutate reducer arguments" (state especially) is very wrong (http://gaearon.github.io/redux/docs/Troubleshooting.html) and I was expecting that when doing this in my reducer:

```javascript
export function reducer(state = {}, action) {
//...
  switch (action.type) {
    case 'SOME_ACTION':
      state.frozen = false
      return state
//...
```
I would leave very soon `shallowEqual` method of react-redux `@connect ` on this test: https://github.com/gaearon/react-redux/blob/master/src/utils/shallowEqual.js#L3

But actually, I was surprised to find out that this test is almost always false and we end up leaving `shallowEqual` only after comparing all props (https://github.com/gaearon/react-redux/blob/master/src/utils/shallowEqual.js#L22). This is due to `combineReducers` https://github.com/gaearon/redux/blob/v1.0.0-rc/src/utils/combineReducers.js#L42 not passing the actual state to `mapValues `. Doing so, `mapValues` always provides a new object (https://github.com/gaearon/redux/blob/v1.0.0-rc/src/utils/mapValues.js#L5) and hence, shallowEqual test cannot leave early when testing current state and new state.

I was then wondering if this was the desired behavior (and if it is, why?) or if there could be some place for improvement by passing the state as initialValue to `mapValues`.

Thanks!

**Comment by gaearon** [comment]
Can you provide a full failing example with actual and expected output? I don't understand what the issue is exactly. If you do something like `connect(state => state)` you're indeed going to have view redrawn every time. However if you `connect(state => state.something)` and that `something` has been mutated by its reducer, the view won't update.

Regardless, `react-redux` seems like the right place to file this issue. It isn't really related to Redux itself, but to `react-redux` update semantics. Please file it there.

**Comment by happypoulp** [comment]
Sorry if I wasn't clear, I should have said in the beginning that it's not a bug.

I was indeed using this `connect` code:

```javascript
@connect(state => state)
export default class SomeComponent extends React.Component {
//...
```

and I know that it is wrong, it was for pure curiosity purpose.

Actually what's funny, is that the view was not redrawn every time. `react-redux` logic was correctly doing its job through `shallowEqual` function but I was expecting to leave shallowEqual on the first test https://github.com/gaearon/react-redux/blob/master/src/utils/shallowEqual.js#L3 since I was mutating the state and returning it from `@connect`. But because of redux `combinerReducers::mapValues` providing a new hash each time it is called, I only leave `shallowEqual` after all props have been compared (and since I mutated the state, all props are actually equals).

Again, this is not an issue, and using `connect(state => state)` is not advised but maybe using the current state as the initial value of `mapValues` of `combineReducers` could make it obvious that mutating the state + using `connect(state => state)` is a complete no way that will result in your views never updating (because you would then compare the same state object ref). That's why I posted this issue here instead of in react-redux because the fix would be done in `combineReducers::mapValues`. The only benefit of this fix would be to avoid comparing all props of state when someone is mutating the state and using `connect(state => state)`.

What troubled me at first was that mutating the state can work (it can result in views being updated) if the state is very simple and if we use a correct `@connect` function:
```javascript
@connect(state => {
  return {
    frozen: state.reducer.frozen,
  }
})
```
so I was only able to "feel" the bad effects of mutating state when I used `connect(state => state)`.

Sorry I could not provide a failing test but nothing actually fails :).

**Comment by gaearon** [comment]
I understand your concern now, but there's nothing we can do (I think?)
We need to return a new object every time from `combineReducers` (otherwise we'd be mutating state ourselves :-)

Am I missing your point?

**Comment by happypoulp** [comment]
> Am I missing your point?

Absolutely not :D. I am the one that completely missed that non-mutating state meant that we have to change the reference of the state at each update (instead of just returning new slices inside the same state as I thought initially).

Thanks a lot for your clarifications!
