### ISSUE TITLE
Is dispatch debounced?

### ISSUE THREAD

**Issue by Jabher** [gaearon/redux#480]
Hi, I'm making a music player with redux and encountered weird behaviour: while I'm dispatching progress state every 250 msec, it still looks like min loop duration is about 1 second.
I just passed store.dispatch to player manager module (as far as it cannot be fitted into common Redux loop due to native stuff emitting events), I really cannot figure out what else can I do to make it smoother.

**Comment by gaearon** [comment]
Sorry, this is still a very vague description to help you. Redux doesn't batch updates by default. In fact if you look into the source, [you'll see that it's just calling the subscriptions synchronously](https://github.com/gaearon/redux/blob/fd7f884b94a28da7a71d0be67da543e46fdc6c17/src/createStore.js#L91-L111). It definitely isn't blocking something by a second. :-)

Maybe, is it your views not updating? This can happen if you mutate the state, for example. See troubleshooting tips for more information: http://gaearon.github.io/redux/docs/Troubleshooting.html

Please reopen if this doesn't help, and you have a reproducible example of the problem so we can investigate it. Without an example, there's nothing we can help you with. :-(

**Comment by Jabher** [comment]
Sorry, my bad, was just emmitting rounded value of progress to myself, so progress events were like 44% - 45% - 45% - 46% and I was not seeing updates.
