### ISSUE TITLE
Redux 1.0.0rc doesn't work with livereactload

### ISSUE THREAD

**Issue by Calvein** [gaearon/redux#482]
I tested livereactload by mixing the todomvc example in this repo and the [gulp version of livereactload] and it worked perfectly.
I tried it with [the new todo example of the new docs] and it only works once but then also trigger this error:

```
invariant.js:43 Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.
```

The next time I save a file, I just have this same error twice. I had the same behaviour on my app that is fairly larger than this example.
I'm not sure if I should have post this in the `livereactload` repo (or both), but I feel that the error is more related to redux. Maybe `livereactload` won't be compatible with redux@1.0.0 and I may have to switch to webpack :(

[Here is the example], just: `npm install` and `npm run dev`

[gulp version of livereactload]: https://github.com/milankinen/livereactload/tree/master/examples/05-build-systems
[the new todo example of the new docs]: http://gaearon.github.io/redux/docs/basics/ExampleTodoList.html
[Here is the example]: https://cdn.fbsbx.com/hphotos-xft1/v/t59.2708-21/11851277_10153500802558774_312773764_n.gz/livereactlod-redux.tar.gz?oh=10e51401aba75cd16f976618f48e342b&oe=55D05C2D&dl=1

**Comment by gaearon** [comment]
This error looks exactly like the error you get when you have a duplicate React in the bundle. Can you verify whether this is what happened?

**Comment by gaearon** [comment]
Also, this is definitely not related to Redux in any way. In fact Redux doesn't even use React.
Please file this in livereactload repo.
