### ISSUE TITLE
Best way to determine state depending on prop(s)? 

### ISSUE THREAD

**Issue by timbur** [gaearon/redux#495]
This is probably a stupid question, as I have a feeling I'm overlooking something obvious or doing something wrong.  :)

Suppose we have a tree of files to explore, and we want to be able to provide an initial state based on the files/directories the user had opened when they were last using the app or possibly based on the project/workspace/whatever.  So imagine we have this initial state serialized as follows:
```js
const open = {
  'redux/src': true,
  'redux/examples': true,
  'redux/examples/counter': true,
  'redux/examples/counter/server.js': true
};
```

And then for each item in the tree (let's call it a `Limb` component), we want to provide `props.isOpen` based on a combination of the `open` state and the `path` prop which is specific to each `Limb`.  And we also want to provide `toggle` prop (function) that updates both the `open` object and `props.isOpen` such that only the `Limb` being toggled is affected.

What's the best way to achieve this with `redux`?

**Comment by gaearon** [comment]
This is not a Redux issue. Redux is not related to React and doesn't deal with props.

You can file your question in React Redux repo instead: https://github.com/gaearon/react-redux

**Comment by timbur** [comment]
Oh, whoops.  https://github.com/gaearon/react-redux/issues/56
