### ISSUE TITLE
Proposal: change custom dispatcher signature

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux#68]
As rightly noted by @vslinko, [it's better to provide `getState` instead of `initialState`](https://github.com/gaearon/redux/pull/60#issuecomment-110298666).

I think I was wrong now when I said [this](https://github.com/gaearon/redux/pull/60#issuecomment-110310113). In fact, I find it now easier to implement composable dispatchers only if each “parent” has the ability to “intercept” both `getState` and `setState`, and if the child can “query” the latest state.

I'm going to keep this open for a while, as I'm still not 100% sure which approach is more correct, but I'm leaning towards `(getState, setState) => action => ()` now as the signature for the dispatcher.

**Comment by acdlite** [comment]
We also need to rethink where the state "lives." In the current version, there's no way for the Redux instance to push a new state atom to the dispatcher — for instance, a call to `Redux::setState()` does not result in the dispatcher's internal state being updated, leading to a divergence.

**Comment by gaearon** [comment]
The thing is, I'm not sure we want to expose `setState` at all. If you need it you may as well create a new Redux instance. And you can always provide the initial state for a Redux instance when creating it.

I want the state flow from dispatcher to Redux and never the other way around. This makes it much easier to create custom dispatchers IMO.

**Comment by gaearon** [comment]
I thought about it a bit more, and the only change I'll probably do here is make `setState` return the state that was set. This satisfies my use case.

**Comment by emmenko** [comment]
So the signature stays the same (with `initialState`) and only `setState` behaves differently?

**Comment by gaearon** [comment]
Yep.

**Comment by emmenko** [comment]
:+1:
