### ISSUE TITLE
Implement devtool hooks

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux#7]
When #6 is done, I want to use it to implement hooks for debugging and time travelling from console.

![](https://pbs.twimg.com/media/CGhoexjVAAE5V4k.png:large)

The API could be something like

```js
ReduxDebug.printLastActions();
ReduxDebug.printLastStates();
ReduxDebug.jumpTo(stateId);
```

etc.

**Comment by dariocravero** [comment]
It would be nice to model this in a flux way so that apps (like a devtools app) can be plugged in on top of it. [Marty has done that already](http://martyjs.org/devtools/). We can use [panels](https://github.com/UXtemple/panels-ui) to present it. I'll be glad to help out with that :)

**Comment by gaearon** [comment]
Yeah, I definitely want to potentially support a DevTools app. I'm not going to write it myself tho, as it's crazy effort and people trying it generally say it wasn't worth it. A separate “debugger” app communicating by sockets that can be displayed in a DevTools container is more like what I envision.

**Comment by dariocravero** [comment]
Good stuff :) I think that in redux's case it might be a different story regarding its use as _hot reloading all the things_ changes the scenario quite a lot and a clear UI to it might be very beneficial to do all that time travelling :)

**Comment by gaearon** [comment]
Agree here. :-)
I'm aiming for something runnable in a month for my talk at ReactEurope so I'm keeping things simple for now.

**Comment by fibric** [comment]
it looks like redux is now turning into an 'isomorphic thing' (or it ever was but api changes make it clearer now). then i suggest to check out https://github.com/caiogondim/logdown

**Comment by gaearon** [comment]
Superseded by #195.

**Comment by tyleranton** [comment]
>A separate “debugger” app communicating by sockets that can be displayed in a DevTools container is more like what I envision.

I'm currently working on that [here](https://github.com/tyleranton/redux-devtools-electron). So far it has been doable (and difficult). At the moment I'm trying to reason about getting Commit, Revert, etc. to work back to the client from the desktop app. 

I plan on building in more devtools features as well (eg. The ability to add action buttons that will trigger your actions in your application).
