### ISSUE TITLE
question: should redux support react-router or other existed react components ?

### ISSUE THREAD

**Issue by tsingson** [gaearon/redux#70]
redux is great concept for flux implement.

from now, the redux use high order function  to reduce the complexation of decouple between react component / action / store.

redux should to support and how to reuse the existed react components ?

**Comment by gaearon** [comment]
You should be able to “just use” any other React components. Do you have specific problems?

**Comment by gaearon** [comment]
Closing, as it's a question rather than an issue. Feel free to continue discussion though!
