### ISSUE TITLE
Support for React Native

### ISSUE THREAD

**Issue by leoasis** [gaearon/redux#71]
I'm currently working on some apps that use React Native. Since this Flux lib really reflects my needs and taste for what I want to do, I would like Redux to be usable in React Native as well. Currently it has a hard dependency on React-web. I believe a similar approach to what's done with [Flummox](https://github.com/acdlite/flummox) is possible here.

What do you think? I can dive into this in a PR if you decide is good to go but not have enough time to do this.

**Comment by gaearon** [comment]
I'd be thrilled to accept a PR adding RN support.

**Comment by acdlite** [comment]
Yeah, Flummox uses a factory to insert the correct version of React and it works well https://github.com/acdlite/flummox/blob/master/src/addons/react-native.js.

**Comment by leoasis** [comment]
Cool! I'll dive into this then!
