### ISSUE TITLE
What advantages over competition?

### ISSUE THREAD

**Issue by briandipalma** [gaearon/redux#8]
I read your flux evolution blog post (very good stuff) and have been looking at the other flux implementations, so far microcosm is looking the best to me. I still have to do research on some of the others you listed but after looking at this projects README I'm not sure I understand what this provides that the other flux implementations you mention don't provide. Could you add a section to the README explaining?

**Comment by gaearon** [comment]
Maybe no particular advantages, I don't know :-).
It's just something I can play with for my talk at React Europe.

The main goal of this library is to prove that Flux can be implemented in a way compatible with full hot reloading (and explore how this can be done). You can run the example code with `npm start`, change action creators or stores, and the new logic will kick in before you refresh.

**Comment by briandipalma** [comment]
Thanks, just trying to decide which library to use as I think your right in calling this an interesting evolution of flux.

**Comment by gaearon** [comment]
For now, Redux is more of an exploration project than a production-ready Flux lib. It may evolve into one later, but no sooner than a few months. You are free to try it and compare with other approaches though! The API is subject to change.

**Comment by asaf** [comment]
@gaearon I was thinking about giving some talk about Redux in the next Israel React Meetup, so if you are willing to share some of your contents from the React-Europe conference it can be awesome :-)

**Comment by gaearon** [comment]
@asaf When is your talk?

**Comment by asaf** [comment]
@gaearon I think the next is not even set yet, so there's enough time, if the content after your talk is going to be public then share it among us :-)
