### ISSUE TITLE
Investigate Flow support

### ISSUE THREAD

**Issue by acdlite** [gaearon/redux#83]
The ES6 support for Flow seems to have improved quite a bit. Not sure if it covers every feature we're currently using (e.g. the bind operator), but it may be worth giving up a few niceties in exchange for type checking.

https://github.com/facebook/flow/blob/master/Changelog.md#v0120

**Comment by gaearon** [comment]
Agreed. Type-checking the insides would be awesome.

**Comment by emmenko** [comment]
Good idea, I was thinking the same after seeing latest release...

**Comment by gaearon** [comment]
Superseded by #290.
