### ISSUE TITLE
Investigate the library size and dependencies

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux#88]
I haven't given much attention to library size or dependencies yet, as we're still figuring out the right API. However, as people start to depend on it, it's a good idea to check whether we're dragging unnecessary polyfills (babel-runtime?) when it's easily avoidable, and whether there's something we could do to reduce the library size (we can start by adding a UMD build and measuring it! ;-)

I'm currently busy but I'd be happy to see somebody investigate this. If you decide to do it, please let us know in this issue!

**Comment by dariocravero** [comment]
@gaearon I think we can close this now :)
