### ISSUE TITLE
Provide JSDoc

### ISSUE THREAD

**Issue by emmenko** [gaearon/redux#89]
Just for keeping track of this.

**Comment by gaearon** [comment]
I'm on board but let's wait for some conclusion on #87.
Should we annotate types both in Flow and in JSDoc? What's the usual approach here?

**Comment by emmenko** [comment]
I haven't used Flow yet, so I can't really say what's the best approach. I think it also depends if you just want JSDoc in the source code or use it to actually generate a documentation website or something like it.

**Comment by gaearon** [comment]
This was done via #300.
