### ISSUE TITLE
getState() in actionCreators returns initial state, not current state after a reload

### ISSUE THREAD

**Issue by aaronjensen** [gaearon/redux#90]
In the example app, `incrementIfOdd` breaks after the first hot reload. `getState` seems to return the initial state rather than the current state.

**Comment by gaearon** [comment]
Good catch, I can reproduce this.

**Comment by gaearon** [comment]
If you'd like to add a failing test for this, I would appreciate it!

**Comment by aaronjensen** [comment]
after looking at it briefly, i'm not sure of how to write a test for it. It looks like a new `Redux` is getting created with a new `initialState` on hot reload, it's not getting the current state from the old `Redux`. I'm still getting my bearings though so that could be wrong...

**Comment by gaearon** [comment]
The test would create two Redux instances, call `redux.replaceDispatcher(nextRedux)`, then fire an action and verify that callback-form action creators still receive the most recent state.

**Comment by gaearon** [comment]
I'm currently looking at the underlying problem, but a test would help make sure I actually fix it correctly. :-)
