### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux#93]
Currently many branches are untested.
See for yourself:

```
git clone https://github.com/gaearon/redux.git
cd redux

npm install
npm run test:cov
```

Here's what I see:

```
=============================== Coverage summary ===============================
Statements   : 93.18% ( 328/352 )
Branches     : 51.72% ( 30/58 )
Functions    : 95.24% ( 60/63 )
Lines        : 93.16% ( 327/351 )
================================================================================
```

You can inspect particular untested branches by running

```
open coverage/lcov-report/index.html 
```

Here's an example of the behavior we should add tests for:

![screen shot 2015-06-14 at 23 29 36](https://cloud.githubusercontent.com/assets/810438/8150314/40c84804-12ed-11e5-8438-fa6008505274.png)

If you'd like to volunteer to help with adding the missing tests, please write in this issue.

**Comment by soen** [comment]
I'd be happy to try and help out where I can. If you can point me in the right direction, I'll start looking at it in the upcoming week.

**Comment by gaearon** [comment]
Thanks, feel free to ask any questions here. You can start with the logic above. Basically it verifies that `Connector`'s `shouldComponentUpdate` works correctly and ignores updates unrelated to the slice of global state that `Connector` is watching.

**Comment by gaearon** [comment]
Here's the kind of test that we need more of: https://github.com/gaearon/redux/pull/107

**Comment by gaearon** [comment]
We're in a much better shape now.

```
=============================== Coverage summary ===============================
Statements   : 99.39% ( 487/490 ), 25 ignored
Branches     : 96.81% ( 182/188 ), 51 ignored
Functions    : 99.07% ( 106/107 ), 2 ignored
Lines        : 99.21% ( 376/379 )
================================================================================
```
