### ISSUE TITLE
Use the Airbnb style in the source

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux#97]
Following @DenisIzmaylov's suggestion in #95, I propose we adopt the [Airbnb styleguide](https://github.com/airbnb/javascript) and change the style if it differs from Airbnb.

If everyone's on board with this, I'd accept a PR that:

* adds as many Airbnb-enforcing style rules to `.eslintrc` as possible
* changes the source and the README to match the styleguide

Thoughts?

**Comment by emmenko** [comment]
Can't we just use their `eslint` rules? 
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/package.json

**Comment by gaearon** [comment]
I guess we can

**Comment by hzoo** [comment]
So you want to extend their rules? ` "extends": "eslint-config-airbnb",`

You can also use the jscs autofix feature to fix most of the whitespace rules
`jscs docs examples scripts src test --preset=airbnb --fix`.
Can probably do a PR later for that.

**Comment by DenisIzmaylov** [comment]
I'm agreed to @hzoo about `eslint-config-airbnb`. Yesterday I had tested "extends" feature of ESLint and it wasn't successful. Now I found that I used old (0.20) version which may not support this feature correctly. I will try with latest (0.23).

**Comment by DenisIzmaylov** [comment]
Ok, in 0.23 it's working nice. But might be we have to upgrade some rules?

**Comment by DenisIzmaylov** [comment]
Finished by https://github.com/gaearon/redux/pull/121

**Comment by ooflorent** [comment]
Can we close it now? @gaearon @DenisIzmaylov

**Comment by DenisIzmaylov** [comment]
I think no. We have to update README examples to match this code style (point #2 from this issue).

**Comment by gaearon** [comment]
I'd say let's close because README is going to be rewritten anyway.
